### PR TITLE
Fix DynamicHMC support and related issues

### LINKED ISSUE #647: DynamicNUTS example not working
I would like to report that the  DynamicNUTS [example](http://turing.ml/docs/dynamichmc/) is not working. Here is the error I receive:

```

Warning: Package Turing does not have DynamicHMC in its dependencies:
│ - If you have Turing checked out for development and have
│   added DynamicHMC as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Turing
└ Loading DynamicHMC into Turing from project dependency, future warnings for Turing are suppressed.
WARNING: using DynamicHMC.NUTS in module Turing conflicts with an existing identifier.
┌ Warning: Error requiring DynamicHMC from Turing:
│ ArgumentError: Package Turing does not have LogDensityProblems in its dependencies:
│ - If you have Turing checked out for development and have
│   added LogDensityProblems as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Turing
│ Stacktrace:
│  [1] require(::Module, ::Symbol) at ./loading.jl:833
│  [2] top-level scope at /Users/christopher.fisher/.julia/packages/Turing/xp88X/src/Turing.jl:34
│  [3] eval(::Module, ::Any) at ./boot.jl:319
│  [4] top-level scope at none:0
│  [5] eval at ./boot.jl:319 [inlined]
│  [6] eval at /Users/christopher.fisher/.julia/packages/Turing/xp88X/src/Turing.jl:1 [inlined]
│  [7] (::getfield(Turing, Symbol("##6#12")))() at /Users/christopher.fisher/.julia/packages/Requires/9Jse8/src/require.jl:67
│  [8] err(::getfield(Turing, Symbol("##6#12")), ::Module, ::String) at /Users/christopher.fisher/.julia/packages/Requires/9Jse8/src/require.jl:38
│  [9] #5 at /Users/christopher.fisher/.julia/packages/Requires/9Jse8/src/require.jl:66 [inlined]
│  [10] withpath(::getfield(Turing, Symbol("##5#11")), ::String) at /Users/christopher.fisher/.julia/packages/Requires/9Jse8/src/require.jl:28
│  [11] #4 at /Users/christopher.fisher/.julia/packages/Requires/9Jse8/src/require.jl:65 [inlined]
│  [12] listenpkg(::getfield(Turing, Symbol("##4#10")), ::Base.PkgId) at /Users/christopher.fisher/.julia/packages/Requires/9Jse8/src/require.jl:13
│  [13] __init__() at /Users/christopher.fisher/.julia/packages/Turing/xp88X/src/Turing.jl:33
│  [14] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:630
│  [15] macro expansion at ./logging.jl:312 [inlined]
│  [16] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:701
│  [17] _require(::Base.PkgId) at ./loading.jl:934
│  [18] require(::Base.PkgId) at ./loading.jl:855
│  [19] macro expansion at ./logging.jl:311 [inlined]
│  [20] require(::Module, ::Symbol) at ./loading.jl:837
│  [21] include_string(::Module, ::String, ::String) at ./loading.jl:1005
│  [22] include_string(::Module, ::String, ::String, ::Int64) at /Users/christopher.fisher/.julia/packages/CodeTools/xGemk/src/eval.jl:30
│  [23] (::getfield(Atom, Symbol("##114#119")){String,Int64,String})() at /Users/christopher.fisher/.julia/packages/Atom/S54BM/src/eval.jl:94
│  [24] withpath(::getfield(Atom, Symbol("##114#119")){String,Int64,String}, ::Nothing) at /Users/christopher.fisher/.julia/packages/CodeTools/xGemk/src/utils.jl:30
│  [25] withpath at /Users/christopher.fisher/.julia/packages/Atom/S54BM/src/eval.jl:46 [inlined]
│  [26] #113 at /Users/christopher.fisher/.julia/packages/Atom/S54BM/src/eval.jl:93 [inlined]
│  [27] with_logstate(::getfield(Atom, Symbol("##113#118")){String,Int64,String}, ::Base.CoreLogging.LogState) at ./logging.jl:397
│  [28] with_logger at ./logging.jl:493 [inlined]
│  [29] #112 at /Users/christopher.fisher/.julia/packages/Atom/S54BM/src/eval.jl:92 [inlined]
│  [30] hideprompt(::getfield(Atom, Symbol("##112#117")){String,Int64,String}) at /Users/christopher.fisher/.julia/packages/Atom/S54BM/src/repl.jl:87
│  [31] macro expansion at /Users/christopher.fisher/.julia/packages/Atom/S54BM/src/eval.jl:91 [inlined]
│  [32] (::getfield(Atom, Symbol("##111#116")))(::Dict{String,Any}) at /Users/christopher.fisher/.julia/packages/Atom/S54BM/src/eval.jl:86
│  [33] handlemsg(::Dict{String,Any}, ::Dict{String,Any}) at /Users/christopher.fisher/.julia/packages/Atom/S54BM/src/comm.jl:164
│  [34] (::getfield(Atom, Symbol("##19#21")){Array{Any,1}})() at ./task.jl:259
└ @ Requires ~/.julia/packages/Requires/9Jse8/src/require.jl:40

```
After running `]resolve`, I receive the following error:

```
UndefVarError: DynamicNUTS not defined
top-level scope at none:0

```

Here is my system information:

Operating System: OS X 10.11.6

Version:

```
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Xeon(R) CPU E5-1680 v2 @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, ivybridge)
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_EDITOR = atom -a
  JULIA_CMDSTAN_HOME = /Users/christopher.fisher/Documents/cmdstan
```
Packages:
```
(v1.0) pkg> st
    Status `~/.julia/environments/v1.0/Project.toml`
  [7d9fca2a] Arpack v0.3.0+ #43d31d1 (https://github.com/JuliaLinearAlgebra/Arpack.jl.git)
  [c52e3926] Atom v0.7.12
  [6e4b80f9] BenchmarkTools v0.4.1
  [336ed68f] CSV v0.4.3
  [159f3aea] Cairo v0.5.6
  [593b3428] CmdStan v4.5.1
  [35d6a980] ColorSchemes v2.0.1
  [861a8166] Combinatorics v0.7.0
  [34da2185] Compat v1.4.0
  [a93c6f00] DataFrames v0.16.0
  [864edb3b] DataStructures v0.15.0
  [39dd38d3] Dierckx v0.4.1
  [0c46a032] DifferentialEquations v5.3.1
  [31c24e10] Distributions v0.16.4
  [bbc10e6e] DynamicHMC v1.0.2
  [7a1cc6ca] FFTW v0.2.4
  [587475ba] Flux v0.7.0
  [38e38edf] GLM v1.0.2
  [19dc6840] HCubature v1.2.0
  [d9be37ee] Homebrew v0.7.1
  [a98d9a8b] Interpolations v0.11.1
  [682c06a0] JSON v0.20.0
  [e5e0dc1b] Juno v0.5.3
  [b964fa9f] LaTeXStrings v1.0.3
  [984bce1d] LambertW v0.4.3
  [1671dc4f] MCMCChain v0.2.2
  [6e857e4b] MCMCDiagnostics v0.3.0
  [5424a776] Mamba v0.12.0
  [86f7a689] NamedArrays v0.9.2
  [429524aa] Optim v0.17.2
  [3b7a836e] PGFPlots v3.0.1
  [d96e819e] Parameters v0.10.3
  [91a5bcdd] Plots v0.22.5
  [438e738f] PyCall v1.18.5
  [d330b81b] PyPlot v2.7.0
  [1fd47b50] QuadGK v2.0.3
  [6f49c342] RCall v0.13.0
  [e6cf234a] RandomNumbers v1.0.3
  [295af30f] Revise v1.0.2
  [80e77ffc] StanDataFrames v4.0.1
  [8f1571ae] StanMCMCChain v4.1.0
  [60ddc479] StatPlots v0.8.2
  [90137ffa] StaticArrays v0.10.2
  [2d09df54] StatisticalRethinking v0.4.0
  [2913bbd2] StatsBase v0.27.0
  [4c63d2b9] StatsFuns v0.7.0
  [24249f21] SymPy v0.8.3
  [fce5fe82] Turing v0.6.4
  [37e2e46d] LinearAlgebra 

```

### PR DESCRIPTION
**Pull request by mohamed82008**
This fixes #647 and other related issues introduced in #626. A little bit of cleanup is also done.

### CODE REVIEW

File: REQUIRE [hunk 1]
```diff
@@ -11,6 +11,7 @@ MacroTools
 StatsFuns 0.7.0
 SpecialFunctions
 Bijectors
+LogDensityProblems
```
Comment (yebai) [inline REQUIRE]: Since `LogDensityProblems` is only required by `DynamicHMC`, can we load it conditionally via `@require` too?

File: src/Turing.jl [hunk 2]
```diff
@@ -24,30 +24,29 @@ using Markdown
...
+@init @require CmdStan="593b3428-ca2f-500c-ae53-031589ec8ddd" @eval begin
+    using CmdStan
+    import CmdStan: Adapt, Hmc
+end
 
-    @require DynamicHMC="bbc10e6e-7c05-544b-b16e-64fede858acb" @eval begin
-        using DynamicHMC, LogDensityProblems
-        using LogDensityProblems: AbstractLogDensityProblem, ValueGradient
+@init @require DynamicHMC="bbc10e6e-7c05-544b-b16e-64fede858acb" @eval begin
+    using .DynamicHMC: NUTS_init_tune_mcmc
```
Comment (yebai) [inline src/Turing.jl]: Is `.` in `.DynamicHMC` necessary here? Seems you didn't use `.` when loading `LogDensityProblems`.

File: src/Turing.jl [hunk 3]
```diff
@@ -24,30 +24,29 @@ using Markdown
...
-        LogDensityProblems.logdensity(::Type{ValueGradient}, ℓ::FunctionLogDensity, x) = ℓ.f(x)::ValueGradient
-    end
+    LogDensityProblems.logdensity(::Type{ValueGradient}, ℓ::FunctionLogDensity, x) = ℓ.f(x)::ValueGradient
 end
+
 import Base: ~, convert, promote_rule, rand, getindex, setindex!
 import Distributions: sample
-import ForwardDiff: gradient
-using Flux.Tracker
+using ForwardDiff: ForwardDiff
```
Comment (yebai) [inline src/Turing.jl]: Maybe silly, what's the diff between `using ForwardDiff: ForwardDiff` and `using ForwardDiff`?

File: src/samplers/hmc.jl [hunk 4]
```diff
@@ -101,17 +101,12 @@ Sampler(alg::Hamiltonian, adapt_conf::DEFAULT_ADAPT_CONF_TYPE) = begin
...
                                 resume_from=nothing,                # chain to continue
                                 reuse_spl_n=0,                      # flag for spl re-using
                                 adapt_conf=STAN_DEFAULT_ADAPT_CONF, # adapt configuration
                 )
-    if ADBACKEND[] == :forward_diff
-        default_chunk_size = CHUNKSIZE[]  # record global chunk size
-        setchunksize(chunk_size)        # set temp chunk size
-    end
-
+
```
Comment (yebai) [inline src/samplers/hmc.jl]: This seems nicer than the old approach!

File: src/core/ad.jl [hunk 5]
```diff
@@ -37,30 +45,18 @@ gradient(
 Computes the gradient of the log joint of `θ` for the model specified by
 `(vi, sampler, model)` using whichever automatic differentation tool is currently active.
 """
-@generated function gradient(
+function gradient(
```
Comment (yebai) [inline src/core/ad.jl]: It's nice to remove `@generated` when possible. Makes the code more readable!

File: src/Turing.jl (hunk 3 above)
Comment (mohamed82008) [reply src/Turing.jl]: `using ForwardDiff` brings in all `names(ForwardDiff)` to the namespace which are the all exports. `using ForwardDiff: ForwardDiff` is similar to `import ForwardDiff` so it only brings in the module name `ForwardDiff` to the namespace. I will change it to `import` if that's more readable.

File: src/Turing.jl (hunk 2 above)
Comment (mohamed82008) [reply src/Turing.jl]: The . is from the Requires.jl README.

> In the `@require` block, or any included files, you can use or import the package, but note that you must use the syntax `using .Gadfly` or `import .Gadfly`, rather than the usual syntax. Otherwise you will get a warning about `Gadfly` not being in dependencies.

The problem with `LogDensityProblems` is that  `Requires` only "loads" `DynamicHMC` by default using the line: `const DynamicHMC = Base.require(Base.PkgId(Base.UUID("bbc10e6e-7c05-544b-b16e-64fede858acb"), "DynamicHMC"))`, which is generated by the `@require` block, bringing only `DynamicHMC` to the namespace. `DynamicHMC` has `LogDensityProblems` in its deps but it only does `using LogDensityProblems: ...`, I cannot bring in `LogDensityProblems` using `DynamicHMC.LogDensityProblems`. 

The only other 2 ways are: 1) to do `using LogDensityProblems` which needs `LogDensityProblems` to be in the `REQUIRE` file, or 2) to use the Requires.jl approach above. The Requires.jl approach seems to work even when the package is not in the `Project.toml` of the environment and just loads the package without complaining about deps. I am not exactly sure how it works tbh, but it seems kind of hackish, since it bypasses regular dependency checks. As you can see, I went with the first approach, but the second is also a candidate, hoping it won't break things. I can ask around Slack to see if it is safe to use or not.

Comment (yebai) [reply src/Turing.jl]: Perhaps split the block into the following? 

```julia

@init @require DynamicHMC="bbc10e6e-7c05-544b-b16e-64fede858acb" @eval begin
    using .DynamicHMC: NUTS_init_tune_mcmc
end

@init @require LogDensityProblems="some unique id" @eval begin
    using .LogDensityProblems: LogDensityProblems, AbstractLogDensityProblem, ValueGradient

    struct FunctionLogDensity{F} <: AbstractLogDensityProblem
      dimension::Int
      f::F
    end

    LogDensityProblems.dimension(ℓ::FunctionLogDensity) = ℓ.dimension

    LogDensityProblems.logdensity(::Type{ValueGradient}, ℓ::FunctionLogDensity, x) = ℓ.f(x)::ValueGradient
end
```

File: src/Turing.jl (hunk 3 above)
Comment (yebai) [reply src/Turing.jl]: Thanks, `using ForwardDiff: ForwardDiff` works fine.

**Comment by yebai** [comment]
@willtebbutt can you take a look at the AD code?

File: src/Turing.jl (hunk 2 above)
Comment (mohamed82008) [reply src/Turing.jl]: This is ok but the only problem with this is that the examples using both `LogDensityProblems` and `DynamicHMC` would need to start with:
```julia
using LogDensityProblems, DynamicHMC, Turing
```

Comment (yebai) [reply src/Turing.jl]: `using LogDensityProblems, DynamicHMC, Turing` should be fine.

BTW, does `using DynamicHMC` load `LogDensityProblems` into Julia?
