### PR TITLE
Fix HMC in Gibbs issue with dynamic models

### LINKED ISSUE #1095: Dynamic models seem to break
On master the following code breaks probably because the size of `m` changes.

```julia
using Turing, Turing.RandomMeasures

@model imm(y, alpha, ::Type{M}=Vector{Float64}) where {M} = begin
    N = length(y)
    rpm = DirichletProcess(alpha)

    z = tzeros(Int, N)
    cluster_counts = tzeros(Int, N)
    fill!(cluster_counts, 0)

    for i in 1:N
        z[i] ~ ChineseRestaurantProcess(rpm, cluster_counts)
        cluster_counts[z[i]] += 1
    end

    Kmax = findlast(!iszero, cluster_counts)
    m = M(undef, Kmax)
    for k = 1:Kmax
        m[k] ~ Normal(m0, s0)
    end
end

model = imm(randn(100), 1.0);
sample(model, Gibbs(PG(10, :z), HMC(0.01, 4, :m), 100);
```

Error message:
```
ERROR: BoundsError: attempt to access 3-element Array{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}},Float64},Float64,3},1} at index [1:4]
Stacktrace:
 [1] throw_boundserror(::Array{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}},Float64},Float64,3},1}, ::Tuple{UnitRange{Int64}}) at ./abstractarray.jl:538
 [2] checkbounds at ./abstractarray.jl:503 [inlined]
 [3] getindex at ./array.jl:750 [inlined]
 [4] macro expansion at /Users/martin/.julia/packages/DynamicPPL/nsoCZ/src/varinfo.jl:0 [inlined]
 [5] newmetadata(::NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}}, ::Val{(:m,)}, ::Array{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}},Float64},Float64,3},1}) at /Users/martin/.julia/packages/DynamicPPL/nsoCZ/src/varinfo.jl:153
 [6] VarInfo at /Users/martin/.julia/packages/DynamicPPL/nsoCZ/src/varinfo.jl:149 [inlined]
 [7] f at /Users/martin/.julia/dev/Turing/src/core/ad.jl:94 [inlined]
 [8] vector_mode_dual_eval(::Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}}, ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}},Float64},Float64,3,Array{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}},Float64},Float64,3},1}}) at /Users/martin/.julia/packages/ForwardDiff/vt5F1/src/apiutils.jl:37
 [9] vector_mode_gradient! at /Users/martin/.julia/packages/ForwardDiff/vt5F1/src/gradient.jl:103 [inlined]
 [10] gradient!(::Array{Float64,1}, ::Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}}, ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}},Float64},Float64,3,Array{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}},Float64},Float64,3},1}}, ::Val{true}) at /Users/martin/.julia/packages/ForwardDiff/vt5F1/src/gradient.jl:35
 [11] gradient!(::Array{Float64,1}, ::Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}}, ::Array{Float64,1}, ::ForwardDiff.GradientConfig{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}},Float64},Float64,3,Array{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#7"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}},Float64},Float64,3},1}}) at /Users/martin/.julia/packages/ForwardDiff/vt5F1/src/gradient.jl:33
 [12] gradient_logp_forward(::Array{Float64,1}, ::DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64}, ::DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}, ::DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}) at /Users/martin/.julia/dev/Turing/src/core/ad.jl:104
 [13] gradient_logp at /Users/martin/.julia/dev/Turing/src/core/ad.jl:68 [inlined]
 [14] ∂logπ∂θ at /Users/martin/.julia/dev/Turing/src/inference/hmc.jl:403 [inlined]
 [15] ∂H∂θ at /Users/martin/.julia/packages/AdvancedHMC/Sn9Ek/src/hamiltonian.jl:28 [inlined]
 [16] phasepoint(::AdvancedHMC.Hamiltonian{AdvancedHMC.Adaptation.UnitEuclideanMetric{Float64,Tuple{Int64}},Turing.Inference.var"#logπ#48"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}},Turing.Inference.var"#∂logπ∂θ#47"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}}}, ::Array{Float64,1}, ::Array{Float64,1}) at /Users/martin/.julia/packages/AdvancedHMC/Sn9Ek/src/hamiltonian.jl:59
 [17] step(::Random._GLOBAL_RNG, ::AdvancedHMC.Hamiltonian{AdvancedHMC.Adaptation.UnitEuclideanMetric{Float64,Tuple{Int64}},Turing.Inference.var"#logπ#48"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}},Turing.Inference.var"#∂logπ∂θ#47"{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}},DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}}}, ::AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}}, ::AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}) at /Users/martin/.julia/packages/AdvancedHMC/Sn9Ek/src/hamiltonian.jl:135
 [18] #step!#46(::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:iteration,),Tuple{Int64}}}, ::typeof(AbstractMCMC.step!), ::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}, ::DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}, ::Int64) at /Users/martin/.julia/dev/Turing/src/inference/hmc.jl:360
 [19] #step!#70(::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:iteration,),Tuple{Int64}}}, ::typeof(AbstractMCMC.step!), ::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}, ::DynamicPPL.Sampler{Gibbs{(:z, :m),Tuple{PG{(:z,)},HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric}}},Turing.Inference.GibbsState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Tuple{DynamicPPL.Sampler{PG{(:z,)},Turing.Inference.PGState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Float64}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}}}}, ::Int64) at ./none:0
 [20] #step! at ./none:0 [inlined]
 [21] #sample#6(::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(sample), ::Random._GLOBAL_RNG, ::DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}, ::DynamicPPL.Sampler{Gibbs{(:z, :m),Tuple{PG{(:z,)},HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric}}},Turing.Inference.GibbsState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Tuple{DynamicPPL.Sampler{PG{(:z,)},Turing.Inference.PGState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Float64}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}}}}, ::Int64) at /Users/martin/.julia/packages/AbstractMCMC/pi3j6/src/AbstractMCMC.jl:217
 [22] #sample at ./none:0 [inlined]
 [23] #sample#5 at /Users/martin/.julia/packages/AbstractMCMC/pi3j6/src/AbstractMCMC.jl:194 [inlined]
 [24] (::StatsBase.var"#kw##sample")(::NamedTuple{(:progress,),Tuple{Bool}}, ::typeof(sample), ::DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}, ::DynamicPPL.Sampler{Gibbs{(:z, :m),Tuple{PG{(:z,)},HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric}}},Turing.Inference.GibbsState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Tuple{DynamicPPL.Sampler{PG{(:z,)},Turing.Inference.PGState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},Float64}},DynamicPPL.Sampler{HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric},Turing.Inference.HMCState{DynamicPPL.VarInfo{NamedTuple{(:z, :m),Tuple{DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:z},Int64},Array{ChineseRestaurantProcess{DirichletProcess{Float64},TArray{Int64,1}},1},Array{DynamicPPL.VarName{:z},1},Array{Int64,1},Array{Set{DynamicPPL.Selector},1}},DynamicPPL.Metadata{Dict{DynamicPPL.VarName{:m},Int64},Array{Normal{Float64},1},Array{DynamicPPL.VarName{:m},1},Array{Float64,1},Array{Set{DynamicPPL.Selector},1}}}},Float64},AdvancedHMC.StaticTrajectory{AdvancedHMC.EndPointTS,AdvancedHMC.Leapfrog{Float64}},AdvancedHMC.Adaptation.NoAdaptation,AdvancedHMC.PhasePoint{Array{Float64,1},AdvancedHMC.DualValue{Float64,Array{Float64,1}}}}}}}}, ::Int64) at ./none:0
 [25] #sample#2(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(sample), ::DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}, ::Gibbs{(:z, :m),Tuple{PG{(:z,)},HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric}}}, ::Int64) at /Users/martin/.julia/dev/Turing/src/inference/Inference.jl:159
 [26] sample(::DynamicPPL.Model{var"##inner_function#4453#43",NamedTuple{(:y, :alpha, :M),Tuple{Array{Float64,1},Float64,Type{Array{Float64,1}}}},DynamicPPL.ModelGen{(:y, :alpha, :M),var"###imm#4467",NamedTuple{(:M,),Tuple{Type{Array{Float64,1}}}}},Val{()}}, ::Gibbs{(:z, :m),Tuple{PG{(:z,)},HMC{Turing.Core.ForwardDiffAD{40},(:m,),AdvancedHMC.Adaptation.UnitEuclideanMetric}}}, ::Int64) at /Users/martin/.julia/dev/Turing/src/inference/Inference.jl:158
```

@mohamed82008 do you have any idea if this is a bug?

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR fixes #1095 by making sure the position in the HMC PhasePoint is of the right length and value.

CC: @xukai92 @trappmartin

### CODE REVIEW

File: src/inference/hmc.jl [hunk 1]
```diff
@@ -337,23 +337,27 @@ function AbstractMCMC.step!(
...
     Turing.DEBUG && @debug "current ϵ: $ϵ"
-    
+
     # Gibbs component specified cares
     if spl.selector.tag != :default
         # Transform the space
         Turing.DEBUG && @debug "X-> R..."
         link!(spl.state.vi, spl)
         runmodel!(model, spl.state.vi, spl)
+        # Get position and log density before transition
```
Comment (xukai92) [inline src/inference/hmc.jl:347]: Why do we move these two lines into the if statement with duplication? Seems that we can just move them ahead of the if statement.

Comment (mohamed82008) [reply src/inference/hmc.jl:347]: I am avoiding calling `vi[spl]` more than once in the first branch.

Comment (mohamed82008) [reply src/inference/hmc.jl:347]: Alternatively,
```julia
    if spl.selector.tag != :default
        # Transform the space
        Turing.DEBUG && @debug "X-> R..."
        link!(spl.state.vi, spl)
        runmodel!(model, spl.state.vi, spl)
    end
    # Get position and log density before transition
    θ_old, log_density_old = spl.state.vi[spl], getlogp(spl.state.vi)
    if spl.selector.tag != :default
        # Update Hamiltonian
        metric = gen_metric(length(θ_old), spl)
        ∂logπ∂θ = gen_∂logπ∂θ(spl.state.vi, spl, model)
        logπ = gen_logπ(spl.state.vi, spl, model)
        spl.state.h = AHMC.Hamiltonian(metric, logπ, ∂logπ∂θ)
        resize!(spl.state.z.θ, length(θ_old))
        spl.state.z.θ .= θ_old
    end
```

Comment (xukai92) [reply src/inference/hmc.jl:347]: I feel this version is better as it avoids a duplicate line. How do you think?

**Comment by trappmartin** [comment]
Cool, thanks!

File: src/inference/hmc.jl [hunk 2]
```diff
@@ -337,23 +337,26 @@ function AbstractMCMC.step!(
...
+    # Get position and log density before transition
+    θ_old, log_density_old = spl.state.vi[spl], getlogp(spl.state.vi)
+    if spl.selector.tag != :default
         # Update Hamiltonian
-        metric = gen_metric(length(spl.state.vi[spl]), spl)
+        metric = gen_metric(length(θ_old), spl)
         ∂logπ∂θ = gen_∂logπ∂θ(spl.state.vi, spl, model)
         logπ = gen_logπ(spl.state.vi, spl, model)
         spl.state.h = AHMC.Hamiltonian(metric, logπ, ∂logπ∂θ)
+        resize!(spl.state.z.θ, length(θ_old))
```
Comment (yebai) [inline src/inference/hmc.jl:356]: It is worth noting that the vanilla HMC with identity mass matrix might be the only sensible HMC sampler for dynamic models for now, since the adaption schedules for step-size and mass matrix are not guaranteed to work well when the static dimensionality condition no longer holds.  

@trappmartin @mohamed82008 @xukai92

Comment (yebai) [reply src/inference/hmc.jl:356]: @trappmartin Maybe add a warning for this in the Infinite Mixture Model example?

Comment (trappmartin) [reply src/inference/hmc.jl:356]: Good point. I'll open a PR for this.
