### PR TITLE
Use accumulators to fix all logp calculations when sampling

### LINKED ISSUE #2617: values of logp in chain do not include logabsdetjac term
### Minimal working example

Note that the original bug report was with `AdvancedMH.RWMH`. However, the same is true of **any** sampler that uses linked VarInfo. For example, `Turing.NUTS` exhibits the same behaviour.

```julia
using Turing, AdvancedMH, Test

@model f() = x ~ LogNormal()
m = f()
c = sample(m, externalsampler(AdvancedMH.RWMH(2); unconstrained = true), 10);

# Fails
@test isapprox(c[:lp], logpdf.(LogNormal(), c[:x]))

# Passes
@test isapprox(c[:lp], logpdf.(Normal(), log.(c[:x])))
```

### Description

Follow-up from https://github.com/TuringLang/Turing.jl/issues/2583.

### Julia version info

```
julia> versioninfo()
Julia Version 1.11.6
Commit 9615af0f269 (2025-07-09 12:58 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

### Manifest

<details><summary>]st --manifest</summary>

```
(Turing) pkg> st --manifest
Project Turing v0.39.5
Status `~/ppl/lib/Manifest.toml`
  [47edcb42] ADTypes v1.15.0
  [621f4979] AbstractFFTs v1.5.0
  [80f14c24] AbstractMCMC v5.6.3
  [7a57a42e] AbstractPPL v0.12.0
  [1520ce14] AbstractTrees v0.4.5
  [7d9f7c33] Accessors v0.1.42
  [79e6a3ab] Adapt v4.3.0
  [0bf59076] AdvancedHMC v0.8.0
  [5b7e9947] AdvancedMH v0.8.8
⌅ [576499cb] AdvancedPS v0.6.2
  [b5ca4192] AdvancedVI v0.4.1
  [66dad0bd] AliasTables v1.1.3
  [dce04be8] ArgCheck v2.5.0
  [4fba245c] ArrayInterface v7.19.0
  [13072b0f] AxisAlgorithms v1.1.0
  [39de3d68] AxisArrays v0.4.7
  [198e06fe] BangBang v0.4.4
  [9718e550] Baselet v0.1.1
  [76274a88] Bijectors v0.15.8
  [082447d4] ChainRules v1.72.5
  [d360d2e6] ChainRulesCore v1.25.2
  [0ca39b1e] Chairmarks v1.3.1
  [9e997f8a] ChangesOfVariables v0.1.10
  [861a8166] Combinatorics v1.0.3
  [38540f10] CommonSolve v0.2.4
  [bbf7d656] CommonSubexpressions v0.3.1
  [34da2185] Compat v4.17.0
  [a33af91c] CompositionsBase v0.1.2
  [88cd18e8] ConsoleProgressMonitor v0.1.2
  [187b0558] ConstructionBase v1.6.0
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.18.22
  [e2d170a0] DataValueInterfaces v1.0.0
  [244e2a9f] DefineSingletons v0.1.2
  [8bb1440f] DelimitedFiles v1.9.1
  [b429d917] DensityInterface v0.4.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.7.2
  [31c24e10] Distributions v0.25.120
  [ced4e74d] DistributionsAD v0.6.58
  [ffbed154] DocStringExtensions v0.9.5
  [366bfd00] DynamicPPL v0.36.15
  [cad2338a] EllipticalSliceSampling v2.0.0
  [4e289a0a] EnumX v1.0.5
  [e2ba6199] ExprTools v0.1.10
  [55351af7] ExproniconLite v0.10.14
  [7a1cc6ca] FFTW v1.9.0
  [9aa1b823] FastClosures v0.3.2
  [1a297f60] FillArrays v1.13.0
  [6a86dc24] FiniteDiff v2.27.0
  [f6369f11] ForwardDiff v1.0.1
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [d9f16b24] Functors v0.5.2
  [46192b85] GPUArraysCore v0.2.0
  [34004b35] HypergeometricFunctions v0.3.28
  [22cec73e] InitialValues v0.3.1
  [a98d9a8b] Interpolations v0.16.1
  [8197267c] IntervalSets v0.7.11
  [3587e190] InverseFunctions v0.1.17
  [41ab1584] InvertedIndices v1.3.1
  [92d709cd] IrrationalConstants v0.2.4
  [c8e1da08] IterTools v1.10.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.7.0
  [682c06a0] JSON v0.21.4
  [ae98c720] Jieko v0.2.1
  [5ab0869b] KernelDensity v0.6.10
  [5be7bae1] LBFGSB v0.4.1
  [8ac3fa9e] LRUCache v1.6.2
  [b964fa9f] LaTeXStrings v1.4.0
  [1d6d02ad] LeftChildRightSiblingTrees v0.2.0
⌅ [6f1fad26] Libtask v0.8.8
  [d3d80556] LineSearches v7.4.0
  [6fdf6af0] LogDensityProblems v2.1.2
  [996a588d] LogDensityProblemsAD v1.13.1
  [2ab3a3ac] LogExpFunctions v0.3.29
  [e6f89c97] LoggingExtras v1.1.0
  [c7f686f2] MCMCChains v7.1.0
  [be115224] MCMCDiagnosticTools v0.3.14
  [e80e1ace] MLJModelInterface v1.11.1
  [1914dd2f] MacroTools v0.5.16
  [dbb5928d] MappedArrays v0.4.2
  [128add7d] MicroCollections v0.2.0
  [e1d29d7a] Missings v1.2.0
  [2e0e35c7] Moshi v0.3.7
  [d41bc354] NLSolversBase v7.10.0
  [77ba4419] NaNMath v1.1.3
  [86f7a689] NamedArrays v0.10.4
  [c020b1a1] NaturalSort v1.0.0
  [6fe1bfb0] OffsetArrays v1.17.0
  [429524aa] Optim v1.13.2
  [3bd65402] Optimisers v0.4.6
  [7f7a1694] Optimization v4.4.0
  [bca83a33] OptimizationBase v2.8.0
  [36348300] OptimizationOptimJL v0.4.3
  [bac558e1] OrderedCollections v1.8.1
  [90014a1f] PDMats v0.11.35
  [d96e819e] Parameters v0.12.3
  [69de0a69] Parsers v2.8.3
  [85a6dd25] PositiveFactorizations v0.2.4
⌅ [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [08abe8d2] PrettyTables v2.4.0
  [33c8b6b6] ProgressLogging v0.1.5
  [92933f4c] ProgressMeter v1.10.4
  [43287f4e] PtrArrays v1.3.0
  [1fd47b50] QuadGK v2.11.2
  [74087812] Random123 v1.7.1
  [e6cf234a] RandomNumbers v1.6.0
  [b3c3ace0] RangeArrays v0.3.2
  [c84ed2f1] Ratios v0.4.5
  [c1ae055f] RealDot v0.1.0
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.34.1
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.1
  [79098fc4] Rmath v0.8.0
  [f2b01f46] Roots v2.2.8
  [7e49a35a] RuntimeGeneratedFunctions v0.5.15
  [26aad666] SSMProblems v0.5.0
⌃ [0bca4576] SciMLBase v2.102.1
  [c0aeaf25] SciMLOperators v1.3.1
  [53ae85a6] SciMLStructures v1.7.0
  [30f210dd] ScientificTypesBase v3.0.0
  [efcf1570] Setfield v1.1.2
  [a2af1166] SortingAlgorithms v1.2.1
  [9f842d2f] SparseConnectivityTracer v0.6.21
  [dc90abb0] SparseInverseSubset v0.1.2
  [0a514795] SparseMatrixColorings v0.4.21
  [276daf66] SpecialFunctions v2.5.1
  [171d559e] SplittablesBase v0.1.15
  [90137ffa] StaticArrays v1.9.13
  [1e83bf80] StaticArraysCore v1.4.3
⌃ [64bff920] StatisticalTraits v3.4.0
  [10745b16] Statistics v1.11.1
  [82ae8749] StatsAPI v1.7.1
  [2913bbd2] StatsBase v0.34.5
  [4c63d2b9] StatsFuns v1.5.0
  [892a3eda] StringManipulation v0.4.1
  [09ab397b] StructArrays v0.7.1
  [2efcf032] SymbolicIndexingInterface v0.3.41
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.1
  [5d786b92] TerminalLoggers v0.1.7
  [28d57a85] Transducers v0.4.84
  [3a884ed6] UnPack v1.0.2
  [efce3f68] WoodburyMatrices v1.0.0
  [700de1a5] ZygoteRules v0.2.7
  [f5851436] FFTW_jll v3.3.11+0
  [1d5cc7b8] IntelOpenMP_jll v2025.0.4+0
  [81d17ec3] L_BFGS_B_jll v3.0.1+0
  [856f044c] MKL_jll v2025.0.1+1
  [efe28fd5] OpenSpecFun_jll v0.5.6+0
  [f50d1b31] Rmath_jll v0.5.1+0
  [1317d2d5] oneTBB_jll v2022.0.0+0
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.11.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [a63ad114] Mmap v1.11.0
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.11.0
  [de0858da] Printf v1.11.0
  [3fa0cd96] REPL v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [1a1011a3] SharedArrays v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.11.0
  [f489334b] StyledStrings v1.11.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [deac9b47] LibCURL_jll v8.6.0+0
  [e37daf67] LibGit2_jll v1.7.2+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.6+0
  [14a3606d] MozillaCACerts_jll v2023.12.12
  [4536629a] OpenBLAS_jll v0.3.27+1
  [05823500] OpenLibm_jll v0.8.5+0
  [bea87d4a] SuiteSparse_jll v7.7.0+0
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.11.0+0
  [8e850ede] nghttp2_jll v1.59.0+0
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated -m`
```
</details>

### PR DESCRIPTION
**Pull request by penelopeysm**
Following on from https://github.com/TuringLang/DynamicPPL.jl/pull/998, this PR:

- in the optimisation code, removes `LogPriorWithoutJacobianAccumulator` as DynamicPPL's `LogPriorAccumulator` now serves this purpose;

- replaces calls to `getlogjoint` with `getlogjoint_internal` for all samplers (as that's what they want);

- closes #2617 by re-calculating logp together with values_as_in_model when constructing a Transition. This also allows us to stick `logprior` and `loglikelihood` terms into the chain (`lp` is still there and refers to the joint).

- does a little tidy-up on MH: previously the sampler state was just a VarInfo, now we bundle the VarInfo together with its internal-logjoint so that the next iteration doesn't need to recalculate the internal-logjoint.

Between #2629 and this PR all the failing tests should be fixed. 🥳  The remaining issues are 1.10 (doesn't understand `[sources]` in Project.toml) and 1.12 (Libtask).

Closes #2617

### CODE REVIEW

**Comment by penelopeysm** [comment]
@mhauru  Sorry this PR is a bit all over the place. The main change is `Transition`, everything else kind of follows from that, but to get the right behaviour I had to make some slightly less trivial changes to MH and externalsampler.

I think all the 1.11 things in CI that we expect to pass are passing. I'd be in favour of releasing DPPL 0.37 in its current state, then we can check that things work on 1.10, before beginning the remaining work on 0.38. Thoughts welcome.

File: src/mcmc/Inference.jl [hunk 1]
```diff
@@ -123,71 +124,94 @@ end
...
+        sampler_transition,
+    )
+        # Re-evaluating the model is unconscionably slow for untyped VarInfo. It's
+        # much faster to convert it to a typed varinfo first, hence this method.
+        # https://github.com/TuringLang/Turing.jl/issues/2604
+        return Transition(model, DynamicPPL.typed_varinfo(untyped_vi), sampler_transition)
+    end
 end
 
 function metadata(t::Transition)
```
Comment (mhauru) [inline src/mcmc/Inference.jl]: I find the name of `metadata` a bit overly general and not very descriptive of what it does. It seems to only be called in `bundle_samples`. Might we want to just inline it into `bundle_samples`?

File: src/mcmc/Inference.jl [hunk 2]
```diff
@@ -461,16 +484,17 @@ function transitions_from_chain(
     chain::MCMCChains.Chains;
     sampler=DynamicPPL.SampleFromPrior(),
 )
-    vi = Turing.VarInfo(model)
+    vi = VarInfo(model)
 
     iters = Iterators.product(1:size(chain, 1), 1:size(chain, 3))
     transitions = map(iters) do (sample_idx, chain_idx)
         # Set variables present in `chain` and mark those NOT present in chain to be resampled.
+        # TODO(DPPL0.37/penelopeysm): Aargh! setval_and_resample!!!! Burn this!!!
```
Comment (mhauru) [inline src/mcmc/Inference.jl]: To be done before release?

File: src/mcmc/sghmc.jl [hunk 3]
```diff
@@ -100,10 +97,13 @@ function AbstractMCMC.step(
 
     # Save new variables and recompute log density.
     vi = DynamicPPL.unflatten(vi, θ)
+    # TODO(penelopeysm): Is this re-evaluation really necessary? For example,
+    # when we calculate the Transition, couldn't we get the log joint out of it
+    # and then use that?
     vi = last(DynamicPPL.evaluate!!(model, vi))
```
Comment (mhauru) [inline src/mcmc/sghmc.jl]: So why do we do this? SGHMCState needs the logp or something like that?

File: test/mcmc/Inference.jl [hunk 4]
```diff
@@ -116,19 +116,16 @@ using Turing
     @testset "Prior" begin
         N = 10_000
 
-        # Note that all chains contain 3 values per sample: 2 variables + log probability
         @testset "Single-threaded vanilla" begin
             chains = sample(StableRNG(seed), gdemo_d(), Prior(), N)
             @test chains isa MCMCChains.Chains
-            @test size(chains) == (N, 3, 1)
```
Comment (mhauru) [inline test/mcmc/Inference.jl:123]: Why remove this? Same for similar lines below.

File: test/mcmc/ess.jl [hunk 5]
```diff
@@ -54,7 +54,7 @@ using Turing
 
         @testset "gdemo with CSMC + ESS" begin
             alg = Gibbs(:s => CSMC(15), :m => ESS())
-            chain = sample(StableRNG(seed), gdemo(1.5, 2.0), alg, 2000)
+            chain = sample(StableRNG(seed), gdemo(1.5, 2.0), alg, 3_000)
```
Comment (mhauru) [inline test/mcmc/ess.jl:57]: Was this failing?

File: src/mcmc/Inference.jl [hunk 6]
```diff
@@ -123,71 +124,94 @@ end
...
+    `sampler_transition` is the transition object returned by the sampler
+    itself and is only used to extract statistics of interest.
+    """
+    function Transition(model::DynamicPPL.Model, vi::AbstractVarInfo, sampler_transition)
+        vi = DynamicPPL.setaccs!!(
+            vi,
+            (
+                DynamicPPL.ValuesAsInModelAccumulator(true),
+                DynamicPPL.LogPriorAccumulator(),
+                DynamicPPL.LogLikelihoodAccumulator(),
```
Comment (mhauru) [inline src/mcmc/Inference.jl:158]: Could these values be used elsewhere, in samplers? For instance, if we evaluate the model once like this for the global varinfo in Gibbs, could that avoid some extra evaluations when setting the state of the next component sampler? My memory of how this works in Gibbs is not very clear.

File: src/mcmc/Inference.jl (hunk 1 above)
Comment (penelopeysm) [reply src/mcmc/Inference.jl]: Hmmm, it's also used in `get_transition_extras`, so not immediately obvious to me how we can inline (without duplicating code).

Would be quite happy to rename though as I too find it confusing. What do you think about either `getstats` (which right now is only defined for individual samplers' `Transition`, and not defined for `Turing.Inference.Transition`) -- or if you want to differentiate it from `t.stat`, `getstats_with_lp`?

I'd hope that all of this can be cleaned up properly in the near future in #2631.

File: src/mcmc/Inference.jl (hunk 2 above)
Comment (penelopeysm) [reply src/mcmc/Inference.jl]: Ooh, okay, this won't be a 0.37 thing. Getting rid of it will be trivial with InitContext but that'll be 0.38. I'll change the comment.

Comment (penelopeysm) [reply src/mcmc/Inference.jl]: Also, just noticed the line below does `model(rng, vi, sampler)`, and that method was removed in DynamicPPL 0.37.

... Which makes me realise that this entire function, `transitions_from_chain`, is not used anywhere, not tested, and not exported.

I think this should just be removed. Looking back at the old code #1567 #1352 this function used to be part of `predict`, and when `predict` was moved to DynamicPPL this wasn't deleted along with it (seems that it's my fault, oops: #2459)

File: test/mcmc/Inference.jl (hunk 4 above)
Comment (penelopeysm) [reply test/mcmc/Inference.jl:123]: The second element of the size is the total number of parameters, plus metadata. Previously, this would have been 3 (two parameters `s` and `m`, plus `lp`). Now, it's 5, because there's also `logprior` and `loglikelihood`.

I think it's just flaky to test with `== 5`. It's a magic number that depends on how we construct the `Transition`, depends on whether we add more metadata to the `Prior` sampler, (e.g. HMC will have far more than 5)

The subsequent lines already check that there's `:s` and `:m`.

Then the other dimensions aren't any of Turing's business. If you call sample with `N` iterations and no multi-chain then it's AbstractMCMC's responsibility to test that dim 1 is `N` and dim 3 is 1. (And that's tested there already)

File: test/mcmc/ess.jl (hunk 5 above)
Comment (penelopeysm) [reply test/mcmc/ess.jl:57]: Yeah. With 2000 iters we get `(s, m) = (2.1840, 1.1757)`, the expected is `(2.0417, 1.1667)` with `atol = 0.1`.

With 3000 iters it's `(2.1089, 1.1780)`.

The reason for the difference (vs main) is the Gibbs-conditioned-observe thing. I don't think it's a huge loss in accuracy, I think it's just an unlucky seed. For example `seed = 46` with just 1000 iters also works.

File: src/mcmc/Inference.jl (hunk 6 above)
Comment (penelopeysm) [reply src/mcmc/Inference.jl:158]: mmm, quite possibly, right now Gibbs just completely ignores the Transition so actually it's wastefully re-evaluating the model once per component sampler per iteration. Not cool. (That was true before this PR as well.)

Right now I'm not sure what we can concretely do about this, but it's obviously suboptimal so I opened #2639 to track this.

File: src/mcmc/sghmc.jl (hunk 3 above)
Comment (penelopeysm) [reply src/mcmc/sghmc.jl]: When I saw this I felt unwilling to do more refactoring to remove it, but looking at it more carefully it seems that the re-evaluation is completely unnecessary.

Much like other samplers, SGHMC only cares that the varinfo contains the right parameters, it doesn't care that the logp is correct.

Comment (penelopeysm) [reply src/mcmc/sghmc.jl]: I've now removed the extra evaluation for SGHMC and SGLD. I tested it out locally and this led to no changes in sampling results.

File: src/mcmc/Inference.jl (hunk 2 above)
Comment (penelopeysm) [reply src/mcmc/Inference.jl]: Removed.

File: src/mcmc/Inference.jl (hunk 1 above)
Comment (mhauru) [reply src/mcmc/Inference.jl]: Both getstats and getstats_with_lp sound fine to me. I'm also okay with keeping as is, especially if it's soon likely to go anyway. Up to you.

File: test/mcmc/Inference.jl (hunk 4 above)
Comment (mhauru) [reply test/mcmc/Inference.jl:123]: I'm not very bothered by this, and we can remove this line. See Slack for more comments.

File: test/mcmc/ess.jl (hunk 5 above)
Comment (mhauru) [reply test/mcmc/ess.jl:57]: Thanks for the explanation, this soothes me, especially that you know why the results changed at all.

File: src/mcmc/Inference.jl (hunk 1 above)
Comment (penelopeysm) [reply src/mcmc/Inference.jl]: OK, let's go with `getstats_with_lp`. I'd like to clean it up, but really not sure about the timescale for that, so I'm happy to take any net improvement.

**Review by mhauru — APPROVED** [review]
