### PR TITLE
Ignore discard_initial and thinning for SMC

### LINKED ISSUE #1811: SMC throws BoundsError when discard_initial > 1 or thinning > 1
This following works on Turing v0.21.1:

```julia
using Turing
# Define a simple Normal model with unknown mean and variance.
@model function gdemo(x, y)
	s² ~ InverseGamma(2, 3)
	m ~ Normal(0, sqrt(s²))
	x ~ Normal(m, sqrt(s²))
	y ~ Normal(m, sqrt(s²))
end

# works
chn = sample(gdemo(1.5, 2), SMC(), 10; discard_initial = 1)
```
changing `discard_initial` (or `thinning`) to a value larger than 1 and an error is thrown:
```julia
# fails
chn = sample(gdemo(1.5, 2), SMC(), 10; discard_initial = 2)

ERROR: BoundsError: attempt to access 10-element Vector{AdvancedPS.Trace{Turing.Essential.TracedModel{AbstractMCMC.AbstractSampler, DynamicPPL.AbstractVarInfo, DynamicPPL.Model, Tuple}}} at index [11]
Stacktrace:
  [1] getindex
    @ ./array.jl:861 [inlined]
  [2] step(::Random._GLOBAL_RNG, model::DynamicPPL.Model{typeof(gdemo), (:x, :y), (), (), Tuple{Float64, Int64}, Tuple{}, DynamicPPL.DefaultContext}, spl::DynamicPPL.Sampler{SMC{(), AdvancedPS.ResampleWithESSThreshold{typeof(AdvancedPS.resample_systematic), Float64}}}, state::Turing.Inference.SMCState{AdvancedPS.ParticleContainer{AdvancedPS.Trace{Turing.Essential.TracedModel{AbstractMCMC.AbstractSampler, DynamicPPL.AbstractVarInfo, DynamicPPL.Model, Tuple}}}, Float64}; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:nparticles,), Tuple{Int64}}})
    @ Turing.Inference ~/.julia/packages/Turing/uMoX1/src/inference/AdvancedSMC.jl:147
  [3] macro expansion
    @ ~/.julia/packages/AbstractMCMC/0eT8o/src/sample.jl:163 [inlined]
  [4] macro expansion
    @ ~/.julia/packages/ProgressLogging/6KXlp/src/ProgressLogging.jl:328 [inlined]
  [5] macro expansion
    @ ~/.julia/packages/AbstractMCMC/0eT8o/src/logging.jl:9 [inlined]
  [6] mcmcsample(rng::Random._GLOBAL_RNG, model::DynamicPPL.Model{typeof(gdemo), (:x, :y), (), (), Tuple{Float64, Int64}, Tuple{}, DynamicPPL.DefaultContext}, sampler::DynamicPPL.Sampler{SMC{(), AdvancedPS.ResampleWithESSThreshold{typeof(AdvancedPS.resample_systematic), Float64}}}, N::Int64; progress::Bool, progressname::String, callback::Nothing, discard_initial::Int64, thinning::Int64, chain_type::Type, kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:nparticles,), Tuple{Int64}}})
    @ AbstractMCMC ~/.julia/packages/AbstractMCMC/0eT8o/src/sample.jl:111
  [7] sample(rng::Random._GLOBAL_RNG, model::DynamicPPL.Model{typeof(gdemo), (:x, :y), (), (), Tuple{Float64, Int64}, Tuple{}, DynamicPPL.DefaultContext}, sampler::DynamicPPL.Sampler{SMC{(), AdvancedPS.ResampleWithESSThreshold{typeof(AdvancedPS.resample_systematic), Float64}}}, N::Int64; chain_type::Type, resume_from::Nothing, progress::Bool, kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:discard_initial,), Tuple{Int64}}})
    @ Turing.Inference ~/.julia/packages/Turing/uMoX1/src/inference/AdvancedSMC.jl:91
  [8] #sample#2
    @ ~/.julia/packages/Turing/uMoX1/src/inference/Inference.jl:145 [inlined]
  [9] #sample#1
    @ ~/.julia/packages/Turing/uMoX1/src/inference/Inference.jl:135 [inlined]
 [10] top-level scope
    @ ~/github/juliaPkgs/issues/Turing/smc_issue.jl:14

```

perhaps that in this function `nparticles`

https://github.com/TuringLang/Turing.jl/blob/715dd985ac331f5df26338e6b30ac686015610c4/src/inference/AdvancedSMC.jl#L91-L98

needs to be adjusted for `discard_initial` and `thinning`?

The issue can also be replicated by calling mcmcsample directly:
```julia
import Random
n_iter = 10
AbstractMCMC.mcmcsample(
	Random.GLOBAL_RNG,
	gdemo(1.5, 2),
	DynamicPPL.Sampler(SMC()),
	n_iter;
	chain_type=MCMCChains.Chains, 
	progress=Turing.PROGRESS[],
	nparticles=n_iter,
	discard_initial = 1
)

AbstractMCMC.mcmcsample(
	Random.GLOBAL_RNG,
	gdemo(1.5, 2),
	DynamicPPL.Sampler(SMC()),
	n_iter;
	chain_type=MCMCChains.Chains, 
	progress=Turing.PROGRESS[],
	nparticles=n_iter,
	discard_initial = 2
)
```
No error is thrown if `nparticles` is adjusted for `discard_initial`:
```julia
AbstractMCMC.mcmcsample(
	Random.GLOBAL_RNG,
	gdemo(1.5, 2),
	DynamicPPL.Sampler(SMC()),
	n_iter;
	chain_type=MCMCChains.Chains, 
	progress=Turing.PROGRESS[],
	nparticles= n_iter + 1,
	discard_initial = 2
)
```
If this is as simple as modifying `AbstractMCMC.sample(..., spl::Sampler{<:SMC}; ...)` so that  `nparticles = N * thinning + discard_initial - 1`, I'd be happy to open a PR!

### PR DESCRIPTION
**Pull request by hardikxk**
Fixes #1811 

Added a check if `discard_initial` or `thinning` are passed to SMC a warning will appear instead of a BoundsError

also added regression tests for correct sample count

### CODE REVIEW

File: test/mcmc/particle_mcmc.jl [hunk 1]
```diff
@@ -89,6 +89,26 @@ using Turing
...
+
+        chn = sample(normal(), SMC(), 10; discard_initial=5)
+        @test size(chn, 1) == 10
+        @test chn isa MCMCChains.Chains
+        chn2 = sample(normal(), SMC(), 10; thinning=3)
+        @test size(chn2, 1) == 10
+        @test chn2 isa MCMCChains.Chains
+        chn3 = sample(normal(), SMC(), 10; discard_initial=2, thinning=2)
+        @test size(chn3, 1) == 10
+        @test chn3 isa MCMCChains.Chains
```
Comment (penelopeysm) [inline test/mcmc/particle_mcmc.jl:117]: Could you test that the desired warning is thrown using https://docs.julialang.org/en/v1/stdlib/Test/#Test.@test_logs? e.g.

```julia
@test_logs (:warn, r"will be ignored") sample(...)
```

Comment (hardikxk) [reply test/mcmc/particle_mcmc.jl:117]: Yes ive implemented all the requested changes and pushed them!

if theres anything else that should be corrected please let me know

**Comment by penelopeysm** [comment]
Thank you, that's perfect! I'll run CI and merge once it passes 😊

**Review by penelopeysm — APPROVED** [review]
