### PR TITLE
New Feature: Fix and improve `coeftable` for otpimize() output

### LINKED ISSUE #2033: coeftable on optimize output (MLE and MAP) throws error
I am following the first example mentioned here https://discourse.julialang.org/t/ann-turing-0-13-0-mle-map-and-prediction/40033:

```julia
using Turing
using Optim
using StatsBase

@model function gdemo()
    s ~ InverseGamma(2,3)
    m ~ Normal(0, sqrt(s))

    1.5 ~ Normal(m, sqrt(s))
    2.0 ~ Normal(m, sqrt(s))

    return m, s
end

model = gdemo()

# Use the default optimizer, LBFGS.
mle1 = optimize(model, MLE())

coeftable(mle1)
```

But it throws an error. Am I doing something wrong?

```
ERROR: MethodError: Cannot `convert` an object of type Symbol to an object of type String

Closest candidates are:
  convert(::Type{T}, ::Union{InitialValues.SpecificInitialValue{typeof(*)}, InitialValues.SpecificInitialValue{typeof(Base.mul_prod)}}) where T<:Union{AbstractString, Number}
   @ InitialValues C:\Users\domma\.julia\packages\InitialValues\OWP8V\src\InitialValues.jl:258
  convert(::Type{T}, ::ProgressLogging.ProgressString) where T<:AbstractString
   @ ProgressLogging C:\Users\domma\.julia\packages\ProgressLogging\6KXlp\src\ProgressLogging.jl:211
  convert(::Type{String}, ::String)
   @ Base essentials.jl:298
  ...

Stacktrace:
  [1] StatsBase.NoQuote(s::Symbol)
    @ StatsBase C:\Users\domma\.julia\packages\StatsBase\XgjIN\src\statmodels.jl:111
  [2] (::StatsBase.var"#231#234"{CoefTable, Vector{AbstractVector{Float64}}})(::Tuple{Int64, Int64})
    @ StatsBase .\none:0
  [3] iterate
    @ .\generator.jl:47 [inlined]
  [4] collect(itr::Base.Generator{Base.Iterators.ProductIterator{Tuple{UnitRange{Int64}, UnitRange{Int64}}}, StatsBase.var"#231#234"{CoefTable, Vector{AbstractVector{Float64}}}})
    @ Base .\array.jl:782
  [5] show(io::IOContext{Base.TTY}, ct::CoefTable)
    @ StatsBase C:\Users\domma\.julia\packages\StatsBase\XgjIN\src\statmodels.jl:123
  [6] show(io::IOContext{Base.TTY}, #unused#::MIME{Symbol("text/plain")}, x::CoefTable)
    @ Base.Multimedia .\multimedia.jl:47
  [7] (::REPL.var"#55#56"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL C:\Users\domma\AppData\Local\Programs\Julia-1.9.0\share\julia\stdlib\v1.9\REPL\src\REPL.jl:276
  [8] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL C:\Users\domma\AppData\Local\Programs\Julia-1.9.0\share\julia\stdlib\v1.9\REPL\src\REPL.jl:557
  [9] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)
    @ REPL C:\Users\domma\AppData\Local\Programs\Julia-1.9.0\share\julia\stdlib\v1.9\REPL\src\REPL.jl:262
 [10] display(d::REPL.REPLDisplay, x::Any)
    @ REPL C:\Users\domma\AppData\Local\Programs\Julia-1.9.0\share\julia\stdlib\v1.9\REPL\src\REPL.jl:281
 [11] display(x::Any)
    @ Base.Multimedia .\multimedia.jl:340
 [12] #invokelatest#2
    @ .\essentials.jl:816 [inlined]
 [13] invokelatest
    @ .\essentials.jl:813 [inlined]
 [14] (::VSCodeServer.var"#66#70"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\domma\.vscode\extensions\julialang.language-julia-1.47.2\scripts\packages\VSCodeServer\src\eval.jl:199
 [15] withpath(f::VSCodeServer.var"#66#70"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams}, path::String)
    @ VSCodeServer c:\Users\domma\.vscode\extensions\julialang.language-julia-1.47.2\scripts\packages\VSCodeServer\src\repl.jl:249
 [16] (::VSCodeServer.var"#65#69"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\domma\.vscode\extensions\julialang.language-julia-1.47.2\scripts\packages\VSCodeServer\src\eval.jl:155
 [17] hideprompt(f::VSCodeServer.var"#65#69"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})
    @ VSCodeServer c:\Users\domma\.vscode\extensions\julialang.language-julia-1.47.2\scripts\packages\VSCodeServer\src\repl.jl:38
 [18] (::VSCodeServer.var"#64#68"{Bool, Bool, Bool, Module, String, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\domma\.vscode\extensions\julialang.language-julia-1.47.2\scripts\packages\VSCodeServer\src\eval.jl:126
 [19] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging .\logging.jl:514
 [20] with_logger
    @ .\logging.jl:626 [inlined]
 [21] (::VSCodeServer.var"#63#67"{VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer c:\Users\domma\.vscode\extensions\julialang.language-julia-1.47.2\scripts\packages\VSCodeServer\src\eval.jl:225
 [22] #invokelatest#2
    @ .\essentials.jl:816 [inlined]
 [23] invokelatest(::Any)
    @ Base .\essentials.jl:813
 [24] macro expansion
    @ c:\Users\domma\.vscode\extensions\julialang.language-julia-1.47.2\scripts\packages\VSCodeServer\src\eval.jl:34 [inlined]
 [25] (::VSCodeServer.var"#61#62")()
    @ VSCodeServer .\task.jl:514
```

### PR DESCRIPTION
**Pull request by DominiqueMakowski**
This PR aims at the following:

- [x] Fixes #2033 by converting the symbols to String
- [x] Following [this](https://discourse.julialang.org/t/get-mle-parameters-e-g-p-value-confidence-intervals-from-a-turing-model-using-optim-jl/101433/3) comment, it would be super nice to add indices typically present in coeftables, such as p-values and confidence intervals. I have added (commented out) the code to do so, and I'm happy to include it.
- [x] I would also suggest to rename the columns to make it more comparable to a regular coeftable 

```julia
coeftable(GLM.lm(@formula(y ~ x), DataFrame(x=x, y=y)))
```
```
────────────────────────────────────────────────────────────────────────
                 Coef.  Std. Error     t  Pr(>|t|)  Lower 95%  Upper 95%
────────────────────────────────────────────────────────────────────────
(Intercept)  22.2225      3.59373   6.18    <1e-06  14.9474    29.4977
x             0.482927    0.152752  3.16    0.0031   0.173697   0.792157
────────────────────────────────────────────────────────────────────────
```
  - [x] However, I would make one exception: rename `t` as `z` because as far as I understood this is a z approximation, not a t-based estimation. I know that in [some cases](https://stats.stackexchange.com/a/282007), the parameter is named *t* even though it's a *z*, but I think we could avoid confusion by being transparent

Note: the only changes were done for `StatsBase.coeftable`, the rest is formatting fixes (removal trailing spaces) done by the autoformatter.

Let me know if I should add the suggested changes :)

### CODE REVIEW

**Comment by DominiqueMakowski** [comment]
Done! I've exposed the `level` parameters to match [StatsBase](https://juliastats.org/StatsBase.jl/latest/statmodels/#StatsAPI.coeftable)

Also, but this is more a question, would it be in principle feasible to add a `predict()` method to predict data based on the MLE estimates?

**Comment by torfjelde** [comment]
FYI we already have a `predict` @yebai , it just doesn't do what @DominiqueMakowski mentioned:) But yeah, such a method would be nice to add!

**Comment by DominiqueMakowski** [comment]
> Feel free to open another PR for predict to Turing.jl in the meantime.

That's probably beyond my skills, I'm not even sure where I'd need to start

**Comment by sethaxen** [comment]
> There have been [discussions](https://github.com/TuringLang/AbstractPPL.jl/pull/81) about adding `predict` to `Turing`, although that PR has not been merged yet. Feel free to open another PR for `predict` to Turing.jl in the meantime.

It may have been a mistake to try to get the `predict` overload into AbstractPPL. The original issue was https://github.com/TuringLang/DynamicPPL.jl/issues/466.

**Comment by torfjelde** [comment]
Btw @DominiqueMakowski can you bump the patch version?

File: src/modes/OptimInterface.jl [hunk 1]
```diff
@@ -50,14 +50,23 @@ function Base.show(io::IO, m::ModeResult)
...
-    terms = StatsBase.coefnames(m)
-    estimates = m.values.array[:,1]
+    terms = String.(StatsBase.coefnames(m))
+    estimates = m.values.array[:, 1]
     stderrors = StatsBase.stderror(m)
-    tstats = estimates ./ stderrors
-
-    StatsBase.CoefTable([estimates, stderrors, tstats], ["estimate", "stderror", "tstat"], terms)
+    zscore = estimates ./ stderrors
+    p = 2 * (1 .- cdf.(Normal(0, 1), abs.(zscore)))
```
Comment (devmotion) [inline src/modes/OptimInterface.jl:59]: This could be simplified to
```suggestion
    p = pvalue(Normal(), zscore; tail=:both)
```
(requires Distributions 0.25.90)

File: src/modes/OptimInterface.jl [hunk 2]
```diff
@@ -50,14 +50,23 @@ function Base.show(io::IO, m::ModeResult)
     show(io, m.values.array)
 end
 
-function StatsBase.coeftable(m::ModeResult)
+function StatsBase.coeftable(m::ModeResult; level::Real=0.95)
     # Get columns for coeftable.
-    terms = StatsBase.coefnames(m)
-    estimates = m.values.array[:,1]
+    terms = String.(StatsBase.coefnames(m))
```
Comment (devmotion) [inline src/modes/OptimInterface.jl:55]: IIRC it is more common to write
```suggestion
    terms = string.(StatsBase.coefnames(m))
```

File: src/modes/OptimInterface.jl [hunk 3]
```diff
@@ -50,14 +50,23 @@ function Base.show(io::IO, m::ModeResult)
...
+    estimates = m.values.array[:, 1]
     stderrors = StatsBase.stderror(m)
-    tstats = estimates ./ stderrors
-
-    StatsBase.CoefTable([estimates, stderrors, tstats], ["estimate", "stderror", "tstat"], terms)
+    zscore = estimates ./ stderrors
+    p = 2 * (1 .- cdf.(Normal(0, 1), abs.(zscore)))
+
+    # Confidence interval (CI)
+    q = quantile(Normal(0, 1), 1 - (1 - level) / 2)
```
Comment (devmotion) [inline src/modes/OptimInterface.jl:62]: A bit simpler:
```suggestion
    q = quantile(Normal(), (1 + level) / 2)
```

**Comment by DominiqueMakowski** [comment]
Thanks @devmotion !

> Btw @DominiqueMakowski can you bump the patch version?

How do I do that?

File: src/modes/OptimInterface.jl [hunk 4]
```diff
@@ -50,14 +50,23 @@ function Base.show(io::IO, m::ModeResult)
...
-    terms = StatsBase.coefnames(m)
-    estimates = m.values.array[:,1]
+    terms = string.(StatsBase.coefnames(m))
+    estimates = m.values.array[:, 1]
     stderrors = StatsBase.stderror(m)
-    tstats = estimates ./ stderrors
-
-    StatsBase.CoefTable([estimates, stderrors, tstats], ["estimate", "stderror", "tstat"], terms)
+    zscore = estimates ./ stderrors
+    p = pvalue(Normal(), zscore; tail=:both)
```
[the remark this answers is not in the document]
Comment (devmotion) [reply src/modes/OptimInterface.jl:59]: Yes, Distributions only implements it but does not export it. The easiest/most correct way is probably to load StatsAPI (an indirect dependency of Distributions, StatsBase etc. anyway).

Comment (cpfiffer) [inline src/modes/OptimInterface.jl:59]: Yeah -- @DominiqueMakowski can you add a StatsAPI import and change the above to

```suggestion
    p = StatsAPI.pvalue(Normal(), zscore; tail=:both)
```

**Review by cpfiffer — CHANGES_REQUESTED** [review]
This is _fantastic_ thank you for doing this! I left one minor comment but for the most part I'd be happy to merge this after the tests pass.

File: src/modes/OptimInterface.jl [hunk 5]
```diff
@@ -7,31 +7,32 @@ import ..ForwardDiff
 import NamedArrays
 import StatsBase
 import Printf
+import StatsAPI
```
Comment (DominiqueMakowski) [inline src/modes/OptimInterface.jl:10]: Added the import

Comment (devmotion) [reply src/modes/OptimInterface.jl:10]: You also have to add StatsAPI to the list of dependencies (in Project.toml), together with a compat entry in the `[compat]` section.

Comment (devmotion) [reply src/modes/OptimInterface.jl:10]: I would recommend reading through the Pkg docs regarding how to manage packages and their dependencies (in particular sections 2 to 4): https://pkgdocs.julialang.org/v1/ I also recommend working with project environments whenever working with Julia.

**Comment by DominiqueMakowski** [comment]
> but for the most part I'd be happy to merge this after the tests pass.

We bumped the version, I'm not sure the failing tests are related to this PR

File: src/modes/OptimInterface.jl (hunk 5 above)
Comment (torfjelde) [reply src/modes/OptimInterface.jl:10]: But yeah, we can do it for you, np :+1:

File: src/modes/OptimInterface.jl [hunk 6]
```diff
@@ -50,14 +51,23 @@ function Base.show(io::IO, m::ModeResult)
...
-    terms = StatsBase.coefnames(m)
-    estimates = m.values.array[:,1]
+    terms = string.(StatsBase.coefnames(m))
+    estimates = m.values.array[:, 1]
     stderrors = StatsBase.stderror(m)
-    tstats = estimates ./ stderrors
-
-    StatsBase.CoefTable([estimates, stderrors, tstats], ["estimate", "stderror", "tstat"], terms)
+    zscore = estimates ./ stderrors
+    p = StatsAPI.pvalue(Normal(), zscore; tail=:both)
```
Comment (devmotion) [inline src/modes/OptimInterface.jl:60]:
```suggestion
    p = map(z -> StatsAPI.pvalue(Normal(), z; tail=:both), zscore)
```
should fix the test failures.

Comment (devmotion) [inline src/modes/OptimInterface.jl:60]:
```suggestion
    p = map(z -> StatsAPI.pvalue(Normal(), z; tail=:both), zscore)
```
should fix the test failures.

**Review by cpfiffer — APPROVED** [review]

**Comment by cpfiffer** [comment]
I'm on my phone, could someone tag the registrator?
