### PR TITLE
Always expect a Libtask trace to be present

### LINKED ISSUE #2754: `ProduceLogLikelihoodAccumulator` does not properly accumulate
### Minimal working example

```julia
using AdvancedPS
using DynamicPPL
using Libtask
using Random
using Turing

@model function linear_regression(x, y)
    α ~ Normal(0, 1)
    β ~ Normal(0, 1)
    σ ~ truncated(Cauchy(0, 3); lower=0)

    for t in eachindex(x)
        μ = α + β * x[t]
        y[t] ~ Normal(μ, σ)
    end
end

rng = MersenneTwister(1234)
x, y = rand(rng, 10), rand(rng, 10)
reg_model = linear_regression(x, y)

vi = DynamicPPL.typed_varinfo(VarInfo(rng, reg_model));
_, vi = DynamicPPL.init!!(rng, reg_model, vi, InitFromPrior());

vi = DynamicPPL.setacc!!(vi, Turing.Inference.ProduceLogLikelihoodAccumulator())
vi = DynamicPPL.empty!!(vi)

inner_rng = AdvancedPS._BASE_RNG()
Random.seed!(
    inner_rng, rand(rng, Random.Sampler(rng, typeof(AdvancedPS.state(inner_rng))))
)

trace = AdvancedPS.Trace(reg_model, vi, AdvancedPS.TracedRNG(inner_rng), true);

while true
    score = AdvancedPS.advance!(trace)
    score === nothing && break
    acc_val = trace.model.f.varinfo.accs[:LogLikelihood].logp

    print("score: $(round(score, digits=3))")
    println("\taccumulator: $(round(acc_val, digits=3))")
end
```

### Description

While the model is properly `consumed`, the accumulators don't match with the values begin `produced`. This occurs because in the `tilde_observe` stack, the `varinfo` switches between local and global every other observation.

Ideally, it should be setting the `varinfo` at every call since the accumulator is updating. In fact, when I force `set_trace_local_varinfo_maybe(vi)` at every `tilde_observe` I get the desired results.

I've narrowed it down to something finicky with the overloaded [`tilde_observe`](https://github.com/TuringLang/Turing.jl/blob/main/src/mcmc/particle_mcmc.jl#L425-L445).

### Julia version info

<details><summary>versioninfo()</summary>

```
Julia Version 1.12.3
Commit 966d0af0fdf (2025-12-15 11:20 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 64 × Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, icelake-server)
  GC: Built with stock GC
Threads: 64 default, 1 interactive, 64 GC (on 64 virtual cores)
Environment:
  JULIA_VSCODE_REPL = 1
  JULIA_DEPOT_PATH = [hidden]
  JULIA_PKG_SERVER = pkg.julialang.org
  JULIA_EDITOR = code
```
</details>

### Manifest

<details><summary>]st --manifest</summary>

```
Status `~/code/turing/smc/Manifest.toml`
  [47edcb42] ADTypes v1.21.0
  [621f4979] AbstractFFTs v1.5.0
  [80f14c24] AbstractMCMC v5.11.0
⌅ [7a57a42e] AbstractPPL v0.13.6
  [1520ce14] AbstractTrees v0.4.5
  [7d9f7c33] Accessors v0.1.43
  [79e6a3ab] Adapt v4.4.0
  [0bf59076] AdvancedHMC v0.8.3
  [5b7e9947] AdvancedMH v0.8.9
  [576499cb] AdvancedPS v0.7.2
  [b5ca4192] AdvancedVI v0.6.1
  [66dad0bd] AliasTables v1.1.3
  [dce04be8] ArgCheck v2.5.0
  [4fba245c] ArrayInterface v7.22.0
  [13072b0f] AxisAlgorithms v1.1.0
  [39de3d68] AxisArrays v0.4.8
  [198e06fe] BangBang v0.4.6
  [9718e550] Baselet v0.1.1
  [76274a88] Bijectors v0.15.15
  [082447d4] ChainRules v1.72.6
  [d360d2e6] ChainRulesCore v1.26.0
  [0ca39b1e] Chairmarks v1.3.1
  [9e997f8a] ChangesOfVariables v0.1.10
  [861a8166] Combinatorics v1.1.0
  [38540f10] CommonSolve v0.2.6
  [bbf7d656] CommonSubexpressions v0.3.1
  [34da2185] Compat v4.18.1
  [a33af91c] CompositionsBase v0.1.2
  [88cd18e8] ConsoleProgressMonitor v0.1.2
  [187b0558] ConstructionBase v1.6.0
  [a8cc5b0e] Crayons v4.1.1
  [9a962f9c] DataAPI v1.16.0
  [864edb3b] DataStructures v0.19.3
  [e2d170a0] DataValueInterfaces v1.0.0
  [244e2a9f] DefineSingletons v0.1.2
  [8bb1440f] DelimitedFiles v1.9.1
  [b429d917] DensityInterface v0.4.0
  [163ba53b] DiffResults v1.1.0
  [b552c78f] DiffRules v1.15.1
  [a0c0ee7d] DifferentiationInterface v0.7.14
  [31c24e10] Distributions v0.25.123
  [ced4e74d] DistributionsAD v0.6.58
  [ffbed154] DocStringExtensions v0.9.5
  [366bfd00] DynamicPPL v0.39.11
  [cad2338a] EllipticalSliceSampling v2.0.0
  [4e289a0a] EnumX v1.0.5
  [e2ba6199] ExprTools v0.1.10
  [55351af7] ExproniconLite v0.10.14
  [7a1cc6ca] FFTW v1.10.0
  [9aa1b823] FastClosures v0.3.2
  [1a297f60] FillArrays v1.16.0
  [6a86dc24] FiniteDiff v2.29.0
  [f6369f11] ForwardDiff v1.3.1
  [069b7b12] FunctionWrappers v1.1.3
  [77dc65aa] FunctionWrappersWrappers v0.1.3
  [d9f16b24] Functors v0.5.2
  [46192b85] GPUArraysCore v0.2.0
  [34004b35] HypergeometricFunctions v0.3.28
  [22cec73e] InitialValues v0.3.1
  [a98d9a8b] Interpolations v0.16.2
  [8197267c] IntervalSets v0.7.13
  [3587e190] InverseFunctions v0.1.17
  [41ab1584] InvertedIndices v1.3.1
  [92d709cd] IrrationalConstants v0.2.6
  [c8e1da08] IterTools v1.10.0
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.7.1
  [682c06a0] JSON v1.4.0
  [ae98c720] Jieko v0.2.1
  [5ab0869b] KernelDensity v0.6.10
  [b964fa9f] LaTeXStrings v1.4.0
  [1d6d02ad] LeftChildRightSiblingTrees v0.2.1
  [6f1fad26] Libtask v0.9.10
⌃ [d3d80556] LineSearches v7.5.1
  [6fdf6af0] LogDensityProblems v2.2.0
  [996a588d] LogDensityProblemsAD v1.13.1
  [2ab3a3ac] LogExpFunctions v0.3.29
  [e6f89c97] LoggingExtras v1.2.0
  [c7f686f2] MCMCChains v7.7.0
  [be115224] MCMCDiagnosticTools v0.3.15
  [e80e1ace] MLJModelInterface v1.12.1
  [1914dd2f] MacroTools v0.5.16
  [dbb5928d] MappedArrays v0.4.3
  [128add7d] MicroCollections v0.2.0
  [e1d29d7a] Missings v1.2.0
  [dbe65cb8] MistyClosures v2.1.0
  [2e0e35c7] Moshi v0.3.7
⌅ [d41bc354] NLSolversBase v7.10.0
  [77ba4419] NaNMath v1.1.3
  [86f7a689] NamedArrays v0.10.5
  [c020b1a1] NaturalSort v1.0.0
  [6fe1bfb0] OffsetArrays v1.17.0
⌅ [429524aa] Optim v1.13.3
  [3bd65402] Optimisers v0.4.7
  [7f7a1694] Optimization v5.4.0
  [bca83a33] OptimizationBase v4.2.0
  [36348300] OptimizationOptimJL v0.4.8
  [bac558e1] OrderedCollections v1.8.1
  [90014a1f] PDMats v0.11.37
  [69de0a69] Parsers v2.8.3
  [85a6dd25] PositiveFactorizations v0.2.4
  [d236fae5] PreallocationTools v1.0.0
  [aea7be01] PrecompileTools v1.3.3
  [21216c6a] Preferences v1.5.1
  [08abe8d2] PrettyTables v3.1.2
  [33c8b6b6] ProgressLogging v0.1.6
  [92933f4c] ProgressMeter v1.11.0
  [43287f4e] PtrArrays v1.3.0
  [1fd47b50] QuadGK v2.11.2
  [74087812] Random123 v1.7.1
  [e6cf234a] RandomNumbers v1.6.0
  [b3c3ace0] RangeArrays v0.3.2
  [c84ed2f1] Ratios v0.4.5
  [c1ae055f] RealDot v0.1.0
  [3cdcf5f2] RecipesBase v1.3.4
  [731186ca] RecursiveArrayTools v3.44.0
  [189a3867] Reexport v1.2.2
  [ae029012] Requires v1.3.1
  [79098fc4] Rmath v0.9.0
  [f2b01f46] Roots v2.2.10
  [7e49a35a] RuntimeGeneratedFunctions v0.5.16
  [26aad666] SSMProblems v0.6.1
  [0bca4576] SciMLBase v2.134.0
  [a6db7da4] SciMLLogging v1.8.0
  [c0aeaf25] SciMLOperators v1.14.1
  [431bcebd] SciMLPublic v1.0.1
  [53ae85a6] SciMLStructures v1.10.0
  [30f210dd] ScientificTypesBase v3.0.0
  [efcf1570] Setfield v1.1.2
  [a2af1166] SortingAlgorithms v1.2.2
  [9f842d2f] SparseConnectivityTracer v1.1.3
  [dc90abb0] SparseInverseSubset v0.1.2
  [0a514795] SparseMatrixColorings v0.4.23
  [276daf66] SpecialFunctions v2.6.1
  [171d559e] SplittablesBase v0.1.15
  [90137ffa] StaticArrays v1.9.16
  [1e83bf80] StaticArraysCore v1.4.4
  [64bff920] StatisticalTraits v3.5.0
  [10745b16] Statistics v1.11.1
  [82ae8749] StatsAPI v1.8.0
  [2913bbd2] StatsBase v0.34.10
  [4c63d2b9] StatsFuns v1.5.2
  [892a3eda] StringManipulation v0.4.2
  [09ab397b] StructArrays v0.7.2
  [ec057cc2] StructUtils v2.6.2
  [2efcf032] SymbolicIndexingInterface v0.3.46
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.12.1
  [5d786b92] TerminalLoggers v0.1.7
  [28d57a85] Transducers v0.4.85
  [fce5fe82] Turing v0.42.4
  [efce3f68] WoodburyMatrices v1.1.0
  [700de1a5] ZygoteRules v0.2.7
  [f5851436] FFTW_jll v3.3.11+0
  [1d5cc7b8] IntelOpenMP_jll v2025.2.0+0
  [856f044c] MKL_jll v2025.2.0+0
  [efe28fd5] OpenSpecFun_jll v0.5.6+0
  [f50d1b31] Rmath_jll v0.5.1+0
  [1317d2d5] oneTBB_jll v2022.0.0+1
  [0dad84c5] ArgTools v1.1.2
  [56f22d72] Artifacts v1.11.0
  [2a0f44e3] Base64 v1.11.0
  [ade2ca70] Dates v1.11.0
  [8ba89e20] Distributed v1.11.0
  [f43a241f] Downloads v1.7.0
  [7b1f6079] FileWatching v1.11.0
  [9fa8497b] Future v1.11.0
  [b77e0a4c] InteractiveUtils v1.11.0
  [ac6e5ff7] JuliaSyntaxHighlighting v1.12.0
  [4af54fe1] LazyArtifacts v1.11.0
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2 v1.11.0
  [8f399da3] Libdl v1.11.0
  [37e2e46d] LinearAlgebra v1.12.0
  [56ddb016] Logging v1.11.0
  [d6f4376e] Markdown v1.11.0
  [a63ad114] Mmap v1.11.0
  [ca575930] NetworkOptions v1.3.0
  [44cfe95a] Pkg v1.12.1
  [de0858da] Printf v1.11.0
  [3fa0cd96] REPL v1.11.0
  [9a3f8284] Random v1.11.0
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization v1.11.0
  [1a1011a3] SharedArrays v1.11.0
  [6462fe0b] Sockets v1.11.0
  [2f01184e] SparseArrays v1.12.0
  [f489334b] StyledStrings v1.11.0
  [4607b0f0] SuiteSparse
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test v1.11.0
  [cf7118a7] UUIDs v1.11.0
  [4ec0a83e] Unicode v1.11.0
  [e66e0078] CompilerSupportLibraries_jll v1.3.0+1
  [deac9b47] LibCURL_jll v8.15.0+0
  [e37daf67] LibGit2_jll v1.9.0+0
  [29816b5a] LibSSH2_jll v1.11.3+1
  [14a3606d] MozillaCACerts_jll v2025.5.20
  [4536629a] OpenBLAS_jll v0.3.29+0
  [05823500] OpenLibm_jll v0.8.7+0
  [458c3c95] OpenSSL_jll v3.5.4+0
  [bea87d4a] SuiteSparse_jll v7.8.3+2
  [83775a58] Zlib_jll v1.3.1+2
  [8e850b90] libblastrampoline_jll v5.15.0+0
  [8e850ede] nghttp2_jll v1.64.0+1
  [3f19e933] p7zip_jll v17.7.0+0
```
</details>

### PR DESCRIPTION
**Pull request by penelopeysm**
Closes #2754: with this patch, I get the following results

```julia
julia> while true
           score = AdvancedPS.advance!(trace)
           score === nothing && break
           acc_val = trace.model.f.varinfo.accs[:LogLikelihood].logp

           print("score: $(round(score, digits=3))")
           println("\taccumulator: $(round(acc_val, digits=3))")
       end
score: -3.418	accumulator: 0.0
score: -3.417	accumulator: -3.418
score: -3.417	accumulator: -6.835
score: -3.417	accumulator: -10.252
score: -3.418	accumulator: -13.669
score: -3.417	accumulator: -17.087
score: -3.419	accumulator: -20.505
score: -3.418	accumulator: -23.923
score: -3.417	accumulator: -27.341
score: -3.417	accumulator: -30.758
```

### CODE REVIEW

File: src/mcmc/particle_mcmc.jl [hunk 1]
```diff
@@ -347,102 +347,85 @@ function AbstractMCMC.step(
...
 
 function DynamicPPL.tilde_assume!!(
     ctx::ParticleMCMCContext, dist::Distribution, vn::VarName, vi::AbstractVarInfo
 )
-    arg_vi_id = objectid(vi)
-    vi = get_trace_local_varinfo_maybe(vi)
-    using_local_vi = objectid(vi) == arg_vi_id
-
-    trng = get_trace_local_rng_maybe(ctx.rng)
-    resample = get_trace_local_resampled_maybe(true)
```
Comment (penelopeysm) [inline src/mcmc/particle_mcmc.jl:431]: I think some explanation is necessary, mostly for the unknown future person (which might well be me) who comes across this, and wonders why I got rid of these checks.

Generally, these functions used to attempt to check whether the function was being executed from inside a Libtask taped task. If not, then we attempted to use a "normal" execution path, i.e., using the VarInfo that is passed to tilde_assume!!, etc. -- but if we were, then we had to use the VarInfo that was stored as a 'taped global' in Libtask.

The problem with this is that the check `objectid(vi) == arg_vi_id` used to sometimes return true, *even if there was a trace present*, i.e., even if `get_trace_local_varinfo_maybe` returned the VarInfo stored in the taped globals. I actually completely don't know why. The fact that this was true meant that several lines below this, we never set the VarInfo back in the task's taped globals, which was responsible for the behaviour in #2754.

Why can we remove these checks...? Well, there is no way to actually use `ParticleMCMCContext` without going through `sample(model, ::Union{SMC,PG}, ...)`. That function (technically, the functions that it calls) is what sets the leaf context of a model to be `ParticleMCMCContext`:

https://github.com/TuringLang/Turing.jl/blob/026d07cd03f0929d1d15027acf63adcfeeabd225/src/mcmc/particle_mcmc.jl#L31-L38

It is also what wraps the model in a Libtask trace. (That code is in AdvancedPSLibtaskExt.)

Furthermore, it is meaningless to use `ParticleMCMCContext` outside of a Libtask trace (it is pretty much impossible to run SMC on a Turing model _without_ the functionality that Libtask provides -- trust me, I've tried). So there is a one-to-one correspondence: if you are using `ParticleMCMCContext`, you *are* within a Libtask trace, and vice versa.

So there's really no point in checking whether it is local or not. My current hypothesis is that the check is a vestigial bit of code from the old implementation, which used `SamplingContext{<:SMC}`, and in those cases maybe it was easier to accidentally run into this situation where the model was being executed with that context, but outside of a Libtask trace. Personally, I still don't know how that could ever happen; but anyway, here we are.

Technically, the code that I'm changing here was written in https://github.com/TuringLang/Turing.jl/pull/2585; but the whole logic of 'checking whether we're in a trace or not' predates that PR, so goes back quite a while.

**Comment by penelopeysm** [comment]
CI failures are in the optimisation interface, which is completely unexpected, but also unrelated to this PR, and will be fixed in #2747. It appears to be random since not all runners are failing.
