### PR TITLE
Fix for #1352

### LINKED ISSUE #1352: Wrong prediction results on multivariate params
The `predict` function outputs wrong results depending on how the multivariate parameters are constructed. I present below a simple linear regression problem which always converge fine, but whose `predict` results depend on how the `coef` parameter is constructed.

```julia
using Turing, Plots, StatsPlots
using Turing.Inference: predict

@model function simple_linear(x, y)
    intercept ~ Normal(0,1)

    ## this corrupts `predict` output
    coef ~ MvNormal(2, 1)

    ## this alternative also
    # coef ~ filldist(Normal(0,1), 2)

    ## but this version works fine
    # coef = Vector(undef, 2)
    # for i in axes(coef, 1)
    #     coef[i] ~ Normal(0,1)
    # end

    ## this works too
    # coef1 ~ Normal(0,1)
    # coef2 ~ Normal(0,1)
    # coef = [coef1, coef2]

    coef = reshape(coef, 1, size(x,1))

    mu = intercept .+ coef * x |> vec

    error ~ truncated(Normal(0,1), 0, Inf)

    y ~ MvNormal(mu, error)
end


# simple linear transformation
x = randn(2, 100)
y = [1 + 2 * a + 3 * b for (a,b) in eachcol(x)]

chain = sample(simple_linear(x, y), NUTS(), 1000)

# model converges fine
plot(chain) |> display
@show chain

p = predict(simple_linear(x, missing), chain)

# prediction correctness depends on how multivariate params were constructed
@show y[1]
@show p["y[1]"].value.data |> mean # should be close to y[1] above
@show p["y[1]"].value.data |> std # sould be close to 0.0
```

I'm trying this on Julia 1.4.1 with Turing 0.13.0.

### PR DESCRIPTION
**Pull request by torfjelde**
Fixes #1352 and increases the lower-bound of DynamicPPL (the recent version includes bug-fixes for `predict` and `generated_quantities`).

### CODE REVIEW

File: src/inference/Inference.jl [hunk 1]
```diff
@@ -603,44 +603,23 @@ function transitions_from_chain(
 )
     return transitions_from_chain(Random.GLOBAL_RNG, model, chain; kwargs...)
 end
+
+
```
Comment (devmotion) [inline src/inference/Inference.jl:607]:
```suggestion
```

File: Project.toml [hunk 2]
```diff
@@ -42,7 +42,7 @@ Bijectors = "0.8"
 Distributions = "0.23.3, 0.24"
 DistributionsAD = "0.6"
 DocStringExtensions = "0.8"
-DynamicPPL = "0.10.2"
+DynamicPPL = "0.10.9"
```
Comment (devmotion) [inline Project.toml:45]: I guess we should update the bounds in test/Project.toml as well.

File: src/inference/Inference.jl [hunk 3]
```diff
@@ -649,4 +628,5 @@ function transitions_from_chain(
     return transitions
 end
 
+
```
Comment (devmotion) [inline src/inference/Inference.jl:631]:
```suggestion
```

File: Project.toml (hunk 2 above)
Comment (torfjelde) [reply Project.toml:45]: Done :+1:

**Comment by devmotion** [comment]
The tests fail since Libtask_jll does not support Julia 1.6.0 yet - it will be fixed by https://github.com/JuliaPackaging/Yggdrasil/pull/2176 but the PR depends on https://github.com/JuliaPackaging/Yggdrasil/pull/1987 (see https://github.com/TuringLang/Turing.jl/issues/1554 for more details).

**Comment by devmotion** [comment]
Maybe we should run Turing tests with Julia 1.5, here and in DynamicPPL?

**Comment by torfjelde** [comment]
> Maybe we should run Turing tests with Julia 1.5, here and in DynamicPPL?

Sounds like a good idea to me :+1:

**Comment by torfjelde** [comment]
Just for reference: this is now only waiting on packages to get up-to-date with Bijectors.jl and running #1568

**Comment by devmotion** [comment]
The test error is strange (negative standard deviation in a Normal distribution), do you know what's going on there?

**Comment by torfjelde** [comment]
> The test error is strange (negative standard deviation in a Normal distribution), do you know what's going on there?

Very strange indeed. And no, I don't. It shouldn't have anything to do with this particular PR though :confused:

**Comment by torfjelde** [comment]
It's all the Gibbs-sampler btw

**Comment by torfjelde** [comment]
This should finally be good to go now, once tests pass :+1:

File: src/inference/Inference.jl [hunk 4]
```diff
@@ -517,24 +517,24 @@ function predict(model::Model, chain::MCMCChains.Chains; kwargs...)
     return predict(Random.GLOBAL_RNG, model, chain; kwargs...)
 end
 function predict(rng::AbstractRNG, model::Model, chain::MCMCChains.Chains; include_all = false)
+    # Don't need all the diagnostics
+    chain = MCMCChains.get_sections(chain, :parameters)
```
Comment (devmotion) [inline src/inference/Inference.jl:521]: Can we maybe use different variable names here? It can be a bit tricky, both for the compiler and reader, if different objects of possibly different type share the same name.

**Review by devmotion — COMMENTED** [review]
Looks good, just had a minor suggestion. It seems you also have to update the version number 🙂

File: src/inference/Inference.jl (hunk 4 above)
Comment (torfjelde) [reply src/inference/Inference.jl]: Good point :+1:

**Review by devmotion — APPROVED** [review]

**Comment by torfjelde** [comment]
What in the world. Gibbs is failing again

**Comment by torfjelde** [comment]
I'm very confused by that test. Nothing that I did in the fix for MH and linking changed the behavior of `MH()`, which is NOT linked and uses `StaticProposal`. But now it results in `v2` in the test at https://github.com/TuringLang/Turing.jl/blob/master/test/inference/mh.jl#L149-L152 vanishing, which makes the test fail o.O

Is it okay if I just disable that particular comparison for now and make an issue for it? *Really* want to get the PR merged, and the only thing holding it back is tests unrelated to this PR failing due to random seed :sweat_smile:

**Comment by yebai** [comment]
> Is it okay if I just disable that particular comparison for now and make an issue for it? Really want to get the PR merged, and the only thing holding it back is tests unrelated to this PR failing due to random seed 😅

Happy to merge this PR as-is and open an issue for the failed test.
