### PR TITLE
Compiler refactor 2.0

### LINKED ISSUE #544: Running model without data returns error
```julia
using Turing

@model gdemo(x) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  x[1] ~ Normal(m, sqrt(s))
  x[2] ~ Normal(m, sqrt(s))
  return s, m
end

g = gdemo([1.5, 2]) # This works
g()           # returns: (0.8660317849113424, 0.820409281237518)

g = gdemo() # Returns an error.
g()
```

Here is the error message:
```julia
julia> g = gdemo()
┌ Warning: Data `x` not provided, treating as parameter instead.
└ @ Main ~/.julia/dev/Turing/src/core/compiler.jl:326
[ Info:  Assume - `s` is a parameter
[ Info:  Assume - `m` is a parameter
[ Info:  Assume - `x` is a parameter
gdemo_model (generic function with 4 methods)

julia> g()
ERROR: UndefVarError: x not defined
Stacktrace:
 [1] macro expansion at /Users/hg344/.julia/dev/Turing/src/core/compiler.jl:78 [inlined]
 [2] gdemo_model(::Turing.VarReplay.VarInfo, ::Turing.SampleFromPrior) at /Users/hg344/.julia/packages/MacroTools/4AjBS/src/utils.jl:297 (repeats 2 times)
 [3] top-level scope at none:0
```

@trappmartin

### PR DESCRIPTION
**Pull request by mohamed82008**
# Design summary and remaining tasks

Here is a summary of the new design of the compiler. Please ask questions if something is not clear. As of now, all tests pass.

## Model definition syntax
```julia
@model model_function(x = default_x, y)
	...	
end
```
## Model variables

`args`: `x`, `y`
`dvars`: variables in `args`, not equal to `nothing`, and used in LHS of `~` 
`pvars`: variables used in LHS of `~` and not in `dvars`

When no value is given for `x`, it is treated as a parameter and then initialized to `default_x`.

## Expanded model definition

```julia
model_function(; x = nothing, y = nothing) = model_function(x, y)
function model_function(x = nothing, y = nothing)
    # Get the pvars and dvars from types of x and y in the form of Tuple{:x, :y}.
    # If either is `nothing`, it is not part of the tuple type. This information is available at compile time.
    pvars_tupletype, dvars_tupletype = Turing.get_vars($(Tuple{pvars...}), (x = x, y = y))

    # Get the `data` NamedTuple including only the vars in `dvars_tupletype`, i.e. not equal to `nothing`.
    # This information is available at compile time
    data = Turing.get_data(dvars_tupletype, (x = x, y = y))

    # Define closure signatures.
    closure(sampler::Turing.AnySampler, model) = closure(model)
    closure(model) = closure(Turing.VarInfo(), Turing.SampleFromPrior(), model)
    closure(vi::Turing.VarInfo, model) = closure(vi, Turing.SampleFromPrior(), model)
    function closure(vi::Turing.VarInfo, sampler::Turing.AnySampler, model)
        # Unwrap the `data` NamedTuple to avoid closures. 
        # These if statements are compiled away by the Julia compiler so this will be type stable.
        local x
        if isdefined(model.data, :x)
            x = model.data.x
        else
            x = default_x
        end
        local y
        if isdefined(model.data, :y)
            y = model.data.y
        else
            y = nothing
        end
        vi.logp = zero(Real)
        ...
    end
    
    # Define callable model    
    model = Turing.CallableModel{pvars_tupletype, dvars_tupletype}(closure, data)

    return model
end 
```

## Model

```julia
struct Model{pvars, dvars, F, TD}
    f::F
    data::TD
end
function Model{pvars, dvars}(f::F, data::TD) where {pvars, dvars, F, TD}
    return Model{pvars, dvars, F, TD}(f, data)
end
(m::Model)(args...; kwargs...) = m.f(args..., m; kwargs...)
```

When `m::Model` is called, it simply passes all its `args` and `kwargs` to `m.f` which is the closure defined above, in addition to the model `m` itself which gets passed as an argument. The model `m` is passed as an argument to give `m.f` access to `pvars`, `dvars` and `data`. Variables in `dvars` are [observed](https://github.com/TuringLang/Turing.jl/blob/mt/compiler2.0/src/core/compiler.jl#L76) and variables in `pvars` are [assumed](https://github.com/TuringLang/Turing.jl/blob/mt/compiler2.0/src/core/compiler.jl#L100). This is checked at [compile time](https://github.com/TuringLang/Turing.jl/blob/mt/compiler2.0/src/core/compiler.jl#L176) so the checking statement is optimized away by the Julia compiler. Note that `args` is known when parsing the model, but `pvars` and `dvars` can only be known once we know which of `x` and `y` are defined and which are defaulted to `nothing`. That is only when we know the input types to `model_function`, that we can deduce `pvars` and `dvars` and they never change within the scope of `model_function` or during the lifetime of `closure`.

Finally, any of `x` and `y` that is not `nothing` is put in a `data::NamedTuple` which is a field in the `Model` struct. This then gets unwrapped inside the `closure` body. This avoids the need for closing over `x` and `y`.

This PR also lets us generate the model using keyword arguments as follows: `model_function(y = 1)`, where the unassigned variables are treated as parameters. This lets us define variables in any order or leave them undefined thereof.

- [x] Make `pvars` and `dvars` type information
- [x] Make `data` a field in `CallableModel` and pass it to the closure.
- [x] Fix #544
- [x] Make use of keyword arguments or named tuples in `outer_function` as opposed to simple positional arguments.
- [x] Clean up the compiler, make the variable names more descriptive, and add comments
- [x] Update design above
- [x] Rename `CallableModel` to `Model`
- [x] Use `gensym` for `vi`, `sampler` and `logp`

### CODE REVIEW

File: src/samplers/hmc.jl [hunk 1]
```diff
@@ -47,7 +47,7 @@ function HMC(alg::HMC, new_gid::Int)
 end
 HMC{T}(alg::HMC, new_gid::Int) where {T} = HMC(alg, new_gid)
 
-function hmc_step(θ, lj, lj_func, grad_func, H_func, ϵ, alg::HMC, momentum_sampler::Function;
+function hmc_step(θ, lj, lj_func, grad_func, H_func, ϵ, alg::HMC, momentum_sampler;
```
Comment (trappmartin) [inline src/samplers/hmc.jl]: Why is `momentum_sampler` not a function anymore? Changes on the compiler should not effect this, or?

File: src/samplers/hmc.jl [hunk 2]
```diff
@@ -78,7 +78,7 @@ Sampler(alg::Hamiltonian, adapt_conf::DEFAULT_ADAPT_CONF_TYPE) = begin
     Sampler(alg, info)
 end
 
-function sample(model::Function, alg::Hamiltonian;
+function sample(model, alg::Hamiltonian;
```
Comment (trappmartin) [inline src/samplers/hmc.jl]: `model::CallableModel`?

File: src/samplers/hmc.jl [hunk 3]
```diff
@@ -115,7 +115,7 @@ function sample(model::Function, alg::Hamiltonian;
 
     vi = if resume_from == nothing
         vi_ = VarInfo()
-        Base.invokelatest(model, vi_, HamiltonianRobustInit())
+        model(vi_, HamiltonianRobustInit())
```
Comment (trappmartin) [inline src/samplers/hmc.jl]: 👍

File: src/samplers/hmcda.jl [hunk 4]
```diff
@@ -53,7 +53,7 @@ function HMCDA(n_iters::Int, n_adapts::Int, delta::Float64, lambda::Float64, spa
     return HMCDA(n_iters, n_adapts, delta, lambda, _space, 0)
 end
 
-function hmc_step(θ, lj, lj_func, grad_func, H_func, ϵ, alg::HMCDA, momentum_sampler::Function;
+function hmc_step(θ, lj, lj_func, grad_func, H_func, ϵ, alg::HMCDA, momentum_sampler;
```
Comment (trappmartin) [inline src/samplers/hmcda.jl]: Why does changes on the compiler code change the `momentum_sampler`? I guess this should not be the case.

File: src/samplers/ipmcmc.jl [hunk 5]
```diff
@@ -64,7 +64,7 @@ function Sampler(alg::IPMCMC)
   Sampler(alg, info)
 end
 
-step(model::Function, spl::Sampler{<:IPMCMC}, VarInfos::Array{VarInfo}, is_first::Bool) = begin
+step(model, spl::Sampler{<:IPMCMC}, VarInfos::Array{VarInfo}, is_first::Bool) = begin
```
Comment (trappmartin) [inline src/samplers/ipmcmc.jl]: `model::CallableModel`?

File: src/samplers/ipmcmc.jl [hunk 6]
```diff
@@ -94,7 +94,7 @@ step(model::Function, spl::Sampler{<:IPMCMC}, VarInfos::Array{VarInfo}, is_first
   VarInfos[nodes_permutation]
 end
 
-sample(model::Function, alg::IPMCMC) = begin
+sample(model, alg::IPMCMC) = begin
```
Comment (trappmartin) [inline src/samplers/ipmcmc.jl]: `model::CallableModel`?

File: src/samplers/is.jl [hunk 7]
```diff
@@ -35,7 +35,7 @@ Sampler(alg::IS) = begin
     Sampler(alg, info)
 end
 
-sample(model::Function, alg::IS) = begin
+sample(model, alg::IS) = begin
```
Comment (trappmartin) [inline src/samplers/is.jl]: `model::CallableModel`?

File: src/samplers/mh.jl [hunk 8]
```diff
@@ -68,18 +68,18 @@ Sampler(alg::MH) = begin
   Sampler(alg, info)
 end
 
-propose(model::Function, spl::Sampler{<:MH}, vi::VarInfo) = begin
+propose(model, spl::Sampler{<:MH}, vi::VarInfo) = begin
```
Comment (trappmartin) [inline src/samplers/mh.jl]: `model::CallableModel`?

File: src/samplers/mh.jl [hunk 9]
```diff
@@ -68,18 +68,18 @@ Sampler(alg::MH) = begin
...
   spl.info[:proposal_ratio] = 0.0
   spl.info[:prior_prob] = 0.0
   spl.info[:violating_support] = false
   runmodel!(model, vi ,spl)
 end
 
-function step(model::Function, spl::Sampler{<:MH}, vi::VarInfo, is_first::Val{true})
+function step(model, spl::Sampler{<:MH}, vi::VarInfo, is_first::Val{true})
```
Comment (trappmartin) [inline src/samplers/mh.jl]: `model::CallableModel`?

File: src/samplers/mh.jl [hunk 10]
```diff
@@ -68,18 +68,18 @@ Sampler(alg::MH) = begin
...
   return vi, true
 end
 
-function step(model::Function, spl::Sampler{<:MH}, vi::VarInfo, is_first::Val{false})
+function step(model, spl::Sampler{<:MH}, vi::VarInfo, is_first::Val{false})
```
Comment (trappmartin) [inline src/samplers/mh.jl]: `model::CallableModel`?

File: src/samplers/mh.jl [hunk 11]
```diff
@@ -104,7 +104,7 @@ function step(model::Function, spl::Sampler{<:MH}, vi::VarInfo, is_first::Val{fa
   return vi, is_accept
 end
 
-function sample(model::Function, alg::MH;
+function sample(model, alg::MH;
```
Comment (trappmartin) [inline src/samplers/mh.jl]: `model::CallableModel`?

File: src/samplers/nuts.jl [hunk 12]
```diff
@@ -43,7 +43,7 @@ function NUTS(n_iters::Int, delta::Float64)
 end
 NUTS(alg::NUTS, new_gid::Int) = NUTS(alg.n_iters, alg.n_adapts, alg.delta, alg.space, new_gid)
 
-function hmc_step(θ, lj, lj_func, grad_func, H_func, ϵ, alg::NUTS, momentum_sampler::Function;
+function hmc_step(θ, lj, lj_func, grad_func, H_func, ϵ, alg::NUTS, momentum_sampler;
```
Comment (trappmartin) [inline src/samplers/nuts.jl]: Why does this change?

File: src/samplers/pgibbs.jl [hunk 13]
```diff
@@ -47,9 +47,9 @@ Sampler(alg::PG) = begin
   Sampler(alg, info)
 end
 
-step(model::Function, spl::Sampler{<:PG}, vi::VarInfo, _) = step(model, spl, vi)
+step(model, spl::Sampler{<:PG}, vi::VarInfo, _) = step(model, spl, vi)
```
Comment (trappmartin) [inline src/samplers/pgibbs.jl]: `model::CallableModel`?

File: src/samplers/pgibbs.jl [hunk 14]
```diff
@@ -47,9 +47,9 @@ Sampler(alg::PG) = begin
...
 
-step(model::Function, spl::Sampler{<:PG}, vi::VarInfo) = begin
+step(model, spl::Sampler{<:PG}, vi::VarInfo) = begin
```
Comment (trappmartin) [inline src/samplers/pgibbs.jl]: `model::CallableModel`?

File: src/samplers/pgibbs.jl [hunk 15]
```diff
@@ -79,7 +79,7 @@ step(model::Function, spl::Sampler{<:PG}, vi::VarInfo) = begin
   return particles[indx].vi, true
 end
 
-sample(model::Function, alg::PG;
+sample(model, alg::PG;
```
Comment (trappmartin) [inline src/samplers/pgibbs.jl]: `model::CallableModel`?

File: src/samplers/pmmh.jl [hunk 16]
```diff
@@ -61,7 +61,7 @@ function Sampler(alg::PMMH)
   Sampler(alg, info)
 end
 
-step(model::Function, spl::Sampler{<:PMMH}, vi::VarInfo, is_first::Bool) = begin
+step(model, spl::Sampler{<:PMMH}, vi::VarInfo, is_first::Bool) = begin
```
Comment (trappmartin) [inline src/samplers/pmmh.jl]: `model::CallableModel`?

File: src/samplers/smc.jl [hunk 17]
```diff
@@ -44,7 +44,7 @@ Sampler(alg::SMC) = begin
   Sampler(alg, info)
 end
 
-step(model::Function, spl::Sampler{<:SMC}, vi::VarInfo) = begin
+step(model, spl::Sampler{<:SMC}, vi::VarInfo) = begin
```
Comment (trappmartin) [inline src/samplers/smc.jl]: `model::CallableModel`?

File: src/samplers/smc.jl [hunk 18]
```diff
@@ -68,7 +68,7 @@ step(model::Function, spl::Sampler{<:SMC}, vi::VarInfo) = begin
 end
 
 ## wrapper for smc: run the sampler, collect results.
-function sample(model::Function, alg::SMC)
+function sample(model, alg::SMC)
```
Comment (trappmartin) [inline src/samplers/smc.jl]: `model::CallableModel`?

File: src/samplers/support/hmc_core.jl [hunk 19]
```diff
@@ -122,7 +122,7 @@ end
 
 ###
 
-function runmodel!(model::Function, vi::VarInfo, spl::Union{Nothing,Sampler})
+function runmodel!(model, vi::VarInfo, spl::Union{Nothing,Sampler})
```
Comment (trappmartin) [inline src/samplers/support/hmc_core.jl]: `model::CallableModel`?

File: src/samplers/support/hmc_core.jl [hunk 20]
```diff
@@ -135,7 +135,7 @@ function leapfrog(θ::AbstractVector{<:Real},
                   p::AbstractVector{<:Real},
                   τ::Int,
                   ϵ::Real,
-                  model::Function,
+                  model,
```
Comment (trappmartin) [inline src/samplers/support/hmc_core.jl]: `model::CallableModel`?

File: src/samplers/support/hmc_core.jl [hunk 21]
```diff
@@ -185,12 +185,12 @@ end
 
 function _hmc_step(θ::AbstractVector{<:Real},
                    lj::Real,
-                   lj_func::Function,
-                   grad_func::Function,
-                   H_func::Function,
+                   lj_func,
```
Comment (trappmartin) [inline src/samplers/support/hmc_core.jl]: Why did those change?

File: src/samplers/support/hmc_core.jl [hunk 22]
```diff
@@ -185,12 +185,12 @@ end
...
+                   grad_func,
+                   H_func,
                    τ::Int,
                    ϵ::Real,
-                   momentum_sampler::Function;
+                   momentum_sampler;
```
Comment (trappmartin) [inline src/samplers/support/hmc_core.jl]: Same here. I guess the compiler changes should not affect the `momentum_sampler`. Or what is the rational behind that?

File: src/samplers/support/hmc_core.jl [hunk 23]
```diff
@@ -238,7 +238,7 @@ end
 # TODO: remove used Turing-wrapper functions
 
 # Ref: https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/base_hmc.hpp
-function find_good_eps(model::Function, spl::Sampler{T}, vi::VarInfo) where T
+function find_good_eps(model, spl::Sampler{T}, vi::VarInfo) where T
```
Comment (trappmartin) [inline src/samplers/support/hmc_core.jl]: `model::CallableModel`?

File: test/ad.jl/ad.jl [hunk 24]
```diff
@@ -4,6 +4,7 @@ using Turing: VarInfo, gradient_forward, gradient_reverse
 @model foo_ad() = begin
     x ~ Normal(3, 1)
     y ~ Normal(x, 1)
+    return x, y
```
Comment (trappmartin) [inline test/ad.jl/ad.jl]: A return statement is not mandatory in Turing. Or is it now?

File: test/ad.jl/adr.jl [hunk 25]
```diff
@@ -23,8 +23,8 @@ mvn = collect(Iterators.filter(vn -> vn.sym == :m, keys(vi)))[1]
 _s = getval(vi, svn)[1]
 _m = getval(vi, mvn)[1]
 
-x = map(_->Float64(_), vi[nothing])
-∇E = gradient_reverse(x, vi, ad_test_f)
+x = map(_x->Float64(_x), vi[nothing])
+∇E = gradient_reverse(x, vi, ad_test_f)[2]
```
Comment (trappmartin) [inline test/ad.jl/adr.jl]: I would prefer if `gradient_reverse` would still behave as before. Is there a reason to change it's behavior?

File: test/compiler.jl/model_macro.jl [hunk 26]
```diff
@@ -16,45 +15,17 @@ expr = Turing.generate_observe(:x, :y)
...
-            :kwargs => [],
-            :body => :(return testmodel_comp_model(Turing.VarInfo(), Turing.SampleFromPrior()))
-           )
-@test c[:alias3] == MacroTools.combinedef(alias3)
-@test length(c[:closure].args[2].args[2].args) == 6
-@test mapreduce(line -> line.head == :macrocall, +, c[:closure].args[2].args[2].args) == 4
 
 # check if drawing from the prior works
-@model testmodel0(x) = begin
+@model testmodel0() = begin
```
Comment (trappmartin) [inline test/compiler.jl/model_macro.jl]: Why did you remove the argument?

File: test/compiler.jl/model_macro.jl [hunk 27]
```diff
@@ -16,45 +15,17 @@ expr = Turing.generate_observe(:x, :y)
...
     x ~ Normal()
     return x
 end
 f0_mm = testmodel0()
 @test mean(f0_mm() for _ in 1:1000) ≈ 0. atol=0.1
 
-@model testmodel01(x) = begin
+@model testmodel01() = begin
```
Comment (trappmartin) [inline test/compiler.jl/model_macro.jl]: Why did you remove the argument?

File: test/gibbs.jl/gibbs_constructor.jl [hunk 28]
```diff
@@ -24,14 +24,14 @@ c4 = sample(gdemo(), s4)
 c5 = sample(gdemo(), s5)
 
 # Very loose bound, only for testing constructor.
-for c in [c1, c2, c3 ,c4, c5]
-  check_numerical(c, [:s, :m], [49/24, 7/6], eps=1.0)
-end
+#for c in [c1, c2, c3 ,c4, c5]
```
Comment (trappmartin) [inline test/gibbs.jl/gibbs_constructor.jl]: I suppose this is work in progress. Maybe add something to ensure that this changes will not move into the master.

File: test/hmc_core.jl/bayes_lr.jl [hunk 29]
```diff
@@ -81,9 +81,10 @@ lj = lj_func(θ)
 chn = []
 accept_num = 1
 
-
+#=
```
Comment (trappmartin) [inline test/hmc_core.jl/bayes_lr.jl]: Maybe add a note as a reminder that this should be reverted?

File: test/hmc_core.jl/gdemo_nuts.jl [hunk 30]
```diff
@@ -44,7 +44,7 @@ for test_id = 1:2
 
     totla_num = 10000
     for iter = 1:totla_num
-      
+      global logϵ, lj_func, grad_func, M_adapt, δ, μ
```
Comment (trappmartin) [inline test/hmc_core.jl/gdemo_nuts.jl]: ?

File: test/hmcda.jl/hmcda_geweke.jl [hunk 31]
```diff
@@ -43,7 +43,8 @@ x = [s[:y][1]...]
 s_bk = Array{Turing.Chain}(undef, N)
 
 simple_logger = Base.CoreLogging.SimpleLogger(stderr, Base.CoreLogging.Debug)
-with_logger(simple_logger) do
+Base.CoreLogging.with_logger(simple_logger) do
```
Comment (trappmartin) [inline test/hmcda.jl/hmcda_geweke.jl]: WIP ?

File: src/core/ad.jl [hunk 32]
```diff
@@ -12,7 +12,7 @@ Computes the gradient of the log joint of `θ` for the model specified by
 function gradient(
     θ::AbstractVector{<:Real},
     vi::VarInfo,
-    model::Function,
+    model,
```
[the remark this answers is not in the document]
Comment (trappmartin) [reply src/core/ad.jl]: I think it would be better if this stays to be a function and not `model::CallableModel`. Or not?

**Comment by trappmartin** [comment]
Could you provide a description on the new compiler design on this PR? This would be really helpful. Besides of my comments this looks really nice. Really looking forward to this.

**Comment by mohamed82008** [comment]
Thanks a lot for your comments. I will respond to your comments above, and write a design summary in the weekend. Although the design is still partly being figured out!

File: src/core/ad.jl (hunk 32 above)
[the remark this answers is not in the document]
Comment (mohamed82008) [reply src/core/ad.jl]: A `Function` is too restrictive. Julia lets us use [callable structs](https://docs.julialang.org/en/v1/manual/methods/index.html#Function-like-objects-1) which can store interesting information. The only purposes of input type annotations that I know of in Julia are: 1) to guide dispatch, 2) to throw meaningful errors for user-facing functions, or 3) to signal that a certain interface needs to be defined for the input, e.g. `AbstractVector`. I don't think `Function` is used for dispatch here, and the only "interface" assumed is that it needs to be callable so using `::Function` means more code and less features ;) Think of a user defining their own callable model struct, which can have a `supertype` other than `Function`, and then they want to sample from it. Not restricting the input here means that they can pass their callable struct through and it will just work, at least it should!

File: src/core/compiler.jl [hunk 33]
```diff
@@ -55,19 +61,20 @@ function generate_observe(observation, distribution)
...
 
 """
-function generate_assume(variable, distribution, syms)
-    return esc(
-        quote
+function generate_assume(variable, distribution, compiler)
+    sym, idcs, csym = @VarName(variable)
+    csym = Symbol(compiler[:name], csym)
+    syms = Symbol[csym, variable]
+    return quote
```
[the remark this answers is not in the document]
Comment (mohamed82008) [reply src/core/compiler.jl]: This was needed because the `~` macro was expanded separately, so it needed its own `esc`. Now the `~` expressions are expanded in the `model` macro, so only the `model` macro's `esc` is needed.

File: test/compiler.jl/model_macro.jl (hunk 27 above)
Comment (mohamed82008) [reply test/compiler.jl/model_macro.jl]: This is a mistake. I was testing that it works without `x`, and forgot to add it again, then noticed it after pushing! I will fix it. Thanks for pointing it out.

File: test/gibbs.jl/gibbs_constructor.jl (hunk 28 above)
Comment (mohamed82008) [reply test/gibbs.jl/gibbs_constructor.jl]: Yes I will double check all comments before making this camera-ready.

File: test/hmc_core.jl/bayes_lr.jl (hunk 29 above)
Comment (mohamed82008) [reply test/hmc_core.jl/bayes_lr.jl]: Sure thing.

File: test/hmc_core.jl/gdemo_nuts.jl (hunk 30 above)
Comment (mohamed82008) [reply test/hmc_core.jl/gdemo_nuts.jl]: This was not working when I copied and pasted the code into REPL. The `global` here is needed in Julia 1.0 because the global scoping rules changed. This is a probably skipped file in the tests iiuc, but I am not sure.

File: test/hmcda.jl/hmcda_geweke.jl (hunk 31 above)
Comment (mohamed82008) [reply test/hmcda.jl/hmcda_geweke.jl]: Again was not working when I copied and pasted the code into REPL to check the new compiler works, so I made a quick fix! These should probably be separated out in a separate PR.

File: src/core/compiler.jl [hunk 34]
```diff
@@ -140,67 +143,85 @@ Example:
...
-    return tilde(left, right)
-end
+#macro ~(left, right)
+#    return tilde(left, right)
+#end
 
-function tilde(left, right)
-    return generate_observe(left, right)
+function tilde(left::Number, right, compiler)
+    generate_observe(left, right)
```
[the remark this answers is not in the document]
Comment (mohamed82008) [reply src/core/compiler.jl]: Sure, thanks.

File: src/core/compiler.jl [hunk 35]
```diff
@@ -245,36 +266,29 @@ end
...
-        @warn("Model definition seems empty, still continue.")
-    end
-
+    warn_empty(modeldef[:body])
     # construct compiler dictionary
     compiler = Dict(
         :name => modeldef[:name],
         :closure_name => Symbol(modeldef[:name], :_model),
-        :args => [],
+        :args => modeldef[:args],
```
[the remark this answers is not in the document]
Comment (mohamed82008) [reply src/core/compiler.jl]: Hmm, the whole compiler `Dict` will probably go away or get restructured. I wanted to start with something simple and I believe `compiler[:args]` was being used somewhere with the assumption that it is essentially `modeldef[:args]` so I did this. This may have been a source of errors, so I will double check it next weekend.

File: src/core/trace.jl [hunk 36]
```diff
@@ -8,7 +8,7 @@ mutable struct Trace
 end
 
 # NOTE: this function is called by `forkr`
-function Trace(f::Function)
+function Trace(f)
```
[the remark this answers is not in the document]
Comment (mohamed82008) [reply src/core/trace.jl]: Since I am allowing general callable structs, and passing the `CallableModel` around as if it was a function, this needs to be made generic.

File: src/core/trace.jl [hunk 37]
```diff
@@ -19,7 +19,7 @@ function Trace(f::Function)
   res
 end
 
-function Trace(f::Function, spl::Sampler, vi :: VarInfo)
+function Trace(f, spl::Sampler, vi :: VarInfo)
```
[the remark this answers is not in the document]
Comment (mohamed82008) [reply src/core/trace.jl]: Not necessary; no conflicting `Trace` function signatures, or ambiguity in dispatch, and the parameter is not needed inside the function. `f(vi, spl)` when `f::CallableModel` will just forward the function call to `f.f`.

File: src/samplers/dynamichmc.jl [hunk 38]
```diff
@@ -13,7 +13,7 @@ function Sampler(alg::DynamicNUTS{T}) where T <: Hamiltonian
   return Sampler(alg, Dict{Symbol,Any}())
 end
 
-function sample(model::Function, alg::DynamicNUTS, chunk_size=CHUNKSIZE[]) where T <: Hamiltonian
+function sample(model, alg::DynamicNUTS, chunk_size=CHUNKSIZE[]) where T <: Hamiltonian
```
[the remark this answers is not in the document]
Comment (mohamed82008) [reply src/samplers/dynamichmc.jl]: Possibly, but nothing `CallableModel` specific is used inside, so it can be kept generic to handle all callables.

File: src/samplers/hmc.jl (hunk 1 above)
Comment (mohamed82008) [reply src/samplers/hmc.jl]: If I remember correctly, this was just me getting too `Function`-allergic. I will return it for now.

File: src/samplers/hmc.jl (hunk 2 above)
Comment (mohamed82008) [reply src/samplers/hmc.jl]: Nothing `CallableModel` specific going on inside iiuc.

File: src/samplers/hmcda.jl (hunk 4 above)
Comment (mohamed82008) [reply src/samplers/hmcda.jl]: You are probably right.

File: src/samplers/ipmcmc.jl (hunk 5 above)
Comment (mohamed82008) [reply src/samplers/ipmcmc.jl]: Nothing `CallableModel`-specific inside iiuc.

File: src/samplers/ipmcmc.jl (hunk 6 above)
Comment (mohamed82008) [reply src/samplers/ipmcmc.jl]: Same comment.

File: src/samplers/is.jl (hunk 7 above)
Comment (mohamed82008) [reply src/samplers/is.jl]: Same comment.

File: src/samplers/mh.jl (hunk 8 above)
Comment (mohamed82008) [reply src/samplers/mh.jl]: Same comment.

File: src/samplers/nuts.jl (hunk 12 above)
Comment (mohamed82008) [reply src/samplers/nuts.jl]: It probably shouldn't.

File: src/samplers/support/hmc_core.jl (hunk 21 above)
Comment (mohamed82008) [reply src/samplers/support/hmc_core.jl]: hmm not sure, I will revert them.

File: src/samplers/support/hmc_core.jl (hunk 22 above)
Comment (mohamed82008) [reply src/samplers/support/hmc_core.jl]: You are probably right.

File: test/ad.jl/ad.jl (hunk 24 above)
Comment (mohamed82008) [reply test/ad.jl/ad.jl]: No I don't think so. I will revert this.

File: test/ad.jl/adr.jl (hunk 25 above)
Comment (mohamed82008) [reply test/ad.jl/adr.jl]: This was not doing the expected thing, it was giving an error. I just fixed the error.

Comment (mohamed82008) [reply test/ad.jl/adr.jl]: Wait this may be a bug. I will look into it.

File: test/compiler.jl/model_macro.jl (hunk 26 above)
Comment (mohamed82008) [reply test/compiler.jl/model_macro.jl]: A bug in sampling fake data.

Comment (mohamed82008) [reply test/compiler.jl/model_macro.jl]: I was testing that sampling from prior works, then forgot to add it back.

File: src/core/trace.jl (hunk 37 above)
[the remark this answers is not in the document]
Comment (trappmartin) [reply src/core/trace.jl]: Thanks, now I got it. :)

**Comment by mohamed82008** [comment]
I have added a design summary above. Please let me know if something is not clear or if you want to squeeze more work in this PR.

**Comment by trappmartin** [comment]
Thanks for the effort! I'll have a close look at the PR next week.

**Comment by mohamed82008** [comment]
So while looking further into the type stability of Turing, I thought it may be necessary to de-scope this PR a little to avoid bloating it too much when it doesn't really have to. So I will consider this PR camera-ready if it provides at least the same features we had before, with at least the same speed we had before but without the global scope issue, which means that the `@model` macro can be used in other modules and even inside of functions. Currently, the features are on par IIUC, but the speed has worsened on my local benchmark. So I will look into it. Other big tasks to be done in other PRs include:
1. Making AD mostly type stable (started working on that). This involves encoding the AD type and parameters in the algorithm's type to push the type instability up and allow the user to fully eliminate it. However, it gets a little tricky when deciding the chunk size in `ForwardDiff`. I am saying mostly type stable because `VarInfo`'s type instability infects the AD functions.
2. Making `VarInfo` type stable. This one is very critical as it touches most of the code in `Turing.jl` so I am taking my time thinking about and making thought experiments with potential solutions as I am improving the other bits. I don't really have a feasible solution yet, but a few half-baked proposals which all seem to fail at least one use case in my head. If you have ideas, you can comment in https://github.com/TuringLang/Turing.jl/issues. While I don't have a full-fledged solution, I have a few incremental improvements which are easier to do and should improve the performance IIUC.

**Comment by trappmartin** [comment]
Sounds like a good idea to me. I'll check the PR soon and then we should be ready to go.

Regarding the `VarInfo` type instability. I agree that this is very crucial, we (Hong, Kai and me) had already some discussions on this and I'm happy to jump if I'm of any help. As you said, we should have a good plan for this first. `VarInfo` currently also contains lots of unnecessary fields that we should get rid of.

**Comment by mohamed82008** [comment]
Design description updated above.

**Comment by yebai** [comment]
```julia
sample(gdemo()) # gdemo()()
```

**Comment by mohamed82008** [comment]
@cpfiffer may you please take care of updating the docs after this is merged? The main update I can think of is that there is no need for a section on avoiding the `@model` macro, since it will be perfectly usable in other modules or functions after this PR is merged. You can perhaps rename it to Turing internals or something. I will remove item from the checklist above for now.

**Comment by mohamed82008** [comment]
This is ready for one more review.

**Comment by cpfiffer** [comment]
Can do. Excellent work!

**Comment by yebai** [comment]
> This is ready for one more review.

Thanks, @mohamed82008. I'll take a review this PR soon.

**Comment by mohamed82008** [comment]
Thanks. Btw, this is for you @yebai and @willtebbutt. I hope that's what you meant by phase-based compiler.

https://github.com/TuringLang/Turing.jl/blob/0ecf959b1554cf6df970458d22807e4cf24bda2e/src/core/compiler.jl#L256

**Comment by mohamed82008** [comment]
Thanks for the review @willtebbutt. I will fix it up.

**Comment by willtebbutt** [comment]
> Thanks. Btw, this is for you @yebai and @willtebbutt. I hope that's what you meant by phase-based compiler.

This is the general idea. We'll need a mechanism to allow people to add passes that aren't hard-coded into the compiler though. I'm not sure what that would look like, and we can leave it for another PR.

**Comment by willtebbutt** [comment]
Changes look good to me. Great work @mohamed82008

**Comment by yebai** [comment]
Thanks, @mohamed82008. Could you add a test for https://github.com/TuringLang/Turing.jl/issues/544?

**Comment by mohamed82008** [comment]
Sure, I can do that.

**Comment by trappmartin** [comment]
Look good to me. The only comment I have is that the `sample` function parametrisation is currently inconsistent. Sometimes you changed it to expect a `model::Model` and sometimes a `model`. Maybe it would be good to unify this so that all the `sample` functions expect a `model::Model`?

**Comment by mohamed82008** [comment]
> Maybe it would be good to unify this so that all the sample functions expect a model::Model?

Sure I can do that.
